# Only non-default values are listed here

[licenses]
# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.7 short identifier (+ optional exception)].
allow = [
    "MIT",
    "Apache-2.0",
    "GPL-3.0",
    "Zlib",
    "MPL-2.0",
    "BSD-3-Clause",
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "allow"

