
# cargo-vet config file

[cargo-vet]
version = "0.8"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ciborium]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.gumdrop]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.gumdrop_derive]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.56"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.inotify]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.inotify-sys]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.7.2"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.mime_guess]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.2"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.3"
criteria = "safe-to-run"

[[exemptions.openssl-macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.pretty_assertions]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.procfs]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.prometheus]]
version = "0.13.3"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.2.0"
criteria = "safe-to-run"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-run"

[[exemptions.r2d2]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-run"

[[exemptions.rand_xorshift]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.redox_syscall]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.rusty-fork]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.schannel]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.scheduled-thread-pool]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.5.0"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.37"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.wait-timeout]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.zip]]
version = "0.6.6"
criteria = "safe-to-deploy"
