
# cargo-vet config file

[cargo-vet]
version = "0.7"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cc]]
version = "1.0.79"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.15"
criteria = "safe-to-deploy"

[[exemptions.diesel]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.diesel_derives]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.diesel_table_macro_syntax]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.filetime]]
version = "0.2.21"
criteria = "safe-to-run"

[[exemptions.flate2]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.28"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.gumdrop]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.gumdrop_derive]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.h2]]
version = "0.3.19"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.http]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.http-body]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.httparse]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.hyper]]
version = "0.14.26"
criteria = "safe-to-deploy"

[[exemptions.hyper-tls]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.56"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.3"
criteria = "safe-to-deploy"

[[exemptions.inotify]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.inotify-sys]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.io-lifetimes]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.7.2"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.63"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.144"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.mime]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.mime_guess]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.3"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.2"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.3"
criteria = "safe-to-run"

[[exemptions.openssl-macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.output_vt100]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.7"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.pq-sys]]
version = "0.4.8"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.procfs]]
version = "0.14.2"
criteria = "safe-to-deploy"

[[exemptions.prometheus]]
version = "0.13.3"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.2.0"
criteria = "safe-to-run"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-run"

[[exemptions.r2d2]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-run"

[[exemptions.rand_xorshift]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.8.3"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.6.29"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.reqwest]]
version = "0.11.18"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.36.14"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.37.19"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.rusty-fork]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.21"
criteria = "safe-to-deploy"

[[exemptions.scheduled-thread-pool]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.scoped-tls]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.9.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.163"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.163"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.96"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.1"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.5.0"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.7"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.28.2"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.14"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.19.10"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.37"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.17"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.unicode-bidi]]
version = "0.3.13"
criteria = "safe-to-deploy"

[[exemptions.urlencoding]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.wait-timeout]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.walkdir]]
version = "2.3.3"
criteria = "safe-to-deploy"

[[exemptions.warp]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.36"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-streams]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.63"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.zip]]
version = "0.6.6"
criteria = "safe-to-deploy"
