# generated by rudderc
# @name conditional method
# @version 1.0

function Conditional-Method {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"48da1b53-5c97-4894-acf7-f4d7a0179050"
  $common_params = @{
    ClassPrefix = "/myurl"
    ComponentKey = "/myurl"
    ComponentName = "HTTP request check status with headers"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  Rudder-Report-NA @common_params
}
