[package]
name = "rudder_commons"
version = "0.0.0-dev"
description = "Shared types between agent libraries and policy compiler"
authors = ["Rudder developers <dev@rudder.io>"]
edition = "2021"
readme = "README.adoc"
homepage = "https://www.rudder.io"
repository = "https://github.com/Normation/rudder"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1"
colored = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fancy-regex = "0.11"
nom = "7"
walkdir = "2"
log = "0.4"
regex = "1"
env_logger = "0.10"

[dev-dependencies]
pretty_assertions = "1"