= policy-generation-finished

== When/What ?

This directory contains hooks executed after policies are fully
generated for all nodes, and these new policies are available for
download for the node.

Typically, these hooks are used to log information about the
generation which just happened or notify third parties that
new policies are available (for ex: cf-serverd SIGHUP)

== Parameters

Hooks parameters are passed by environment variable:

- RUDDER_GENERATION_DATETIME       : ISO-8601 YYYY-MM-ddTHH:mm:ss.sssZ
date/time that identifies that policy generation.
- RUDDER_NODE_IDS_PATH             : path to a sourcable file with variable RUDDER_NODE_IDS containing a bash array of node id updated during the process, or the empty array if no nodes were updated.
- RUDDER_END_GENERATION_DATETIME   : ISO-8601 YYYY-MM-ddTHH:mm:ss.sssZ
date/time when the generation ended (minus these hooks)
- RUDDER_NUMBER_NODES_UPDATED      : integer >= 0; number of nodes updated
(could be found by counting $RUDDER_NODE_IDS)
- RUDDER_ROOT_POLICY_SERVER_UPDATED: 0 if root was updated, anything else
if not
