# generated by rudderc
# @name stateless
# @version 1.0

function Stateless {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"b9f8a4d5-ea74-461b-9d0d-81575fa78cc6"
  $common_params = @{
    ClassPrefix = "/var/test"
    ComponentKey = "/var/test"
    ComponentName = "Permissions NTFS"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  $call_params = @{
    Accesstype = "Allow"
    Path = "/var/test"
    PolicyMode = $PolicyMode
    Propagationpolicy = "ThisFolderOnly"
    Rights = "rxw"
    User = "admin"
  }
  $call = Permissions-Ntfs @call_params
  $compute_params = $common_params + @{
    MethodCall = $call
  }
  $context = Compute-Method-Call @compute_params
  $localContext.merge($context)
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"6912f9ff-27f8-42fb-9f38-bd330d64162a"
  $common_params = @{
    ClassPrefix = "/file/path"
    ComponentKey = "/file/path"
    ComponentName = "Permissions (non recursive)"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  Rudder-Report-NA @common_params
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"9a29b174-d512-4534-b58c-7804a1ad990e"
  $common_params = @{
    ClassPrefix = "query;"
    ComponentKey = "query;"
    ComponentName = "Audit from osquery"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  Rudder-Report-NA @common_params
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"43697ece-b31e-4756-ae04-a47c8ab0034d"
  $common_params = @{
    ClassPrefix = "vision"
    ComponentKey = "vision"
    ComponentName = "Monitoring template"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  Rudder-Report-NA @common_params
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"8594e7f6-2f7b-452c-9dac-9b29515797af"
  $common_params = @{
    ClassPrefix = "paramname"
    ComponentKey = "paramname"
    ComponentName = "Monitoring parameter"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  Rudder-Report-NA @common_params
}
