#!/bin/bash

set -ex

##################
### Slow tests ###
##################
if [ "$1" = "--relayd" ]; then
  cd relay/sources && make check
  exit 0
elif [ "$1" = "--language" ]; then
  cd rudder-lang && make test
  exit 0
elif [ "$1" = "--scala" ]; then
  cd webapp/sources && mvn clean install -Dmaven.test.postgres=false
  exit 0
fi

###################
### Quick tests ###
###################
webapp/sources/rudder/rudder-core/src/test/resources/hooks.d/test-hooks.sh

# Python linter
export PYTHONPATH=./relay/sources/rudder-pkg/lib/rudder-pkg/:./relay/sources/rudder-pkg/lib:$PYTHONPATH
find . ! -name 'convertOpenLDAPSchema.py' ! -wholename '*jsondiff/*' -name '*.py' | xargs pylint -E --persistent=n --disable=C,R,import-error,no-member,no-name-in-module
pylint -E --persistent=n --disable=C,R,no-member relay/sources/rudder-pkg/rudder-pkg

# Rudder-pkg check
cd relay/sources/rudder-pkg/lib/rudder-pkg/tests && ./testall && cd -

# Shellcheck
find . -path ./.git -prune -o -type f -exec grep -I -Eq '^#!(.*/|.*env +)(sh|bash|ksh)' {} \; -print |
  while IFS="" read -r file
  do
    # with recent shellcheck, "-S error" replaces this hack
    shellcheck -f gcc "$file" | grep " error: " && exit 1 || true
  done
