#!/bin/bash

make test-common

find . -name '*.py' | xargs pylint -E --disable=C,R --persistent=n
mv ncf test.ncf
pylint -E --disable=C,R --persistent=n --init-hook="sys.path[0:0] = ['./tools']" test.ncf
mv test.ncf ncf
