# @generated by rudderc
# @name unknown
# @version unknown

bundle agent Configure_NTP_technique {
  vars:
    "resources_dir" string => "${this.promise_dirname}/resources";

  methods:
    "${report_data.directive_id}_0" usebundle => _method_reporting_context("any", "/tmp"),
    if => concat("ubuntu");
    "${report_data.directive_id}_1" usebundle => file_absent("/tmp"),
    if => concat("ubuntu");
    "${report_data.directive_id}_2" usebundle => _method_reporting_context("any", "/tmp"),
    if => concat("debian");
    "${report_data.directive_id}_3" usebundle => file_present("/tmp"),
    if => concat("debian");
    "${report_data.directive_id}_4" usebundle => ncf_log(info: ok);
}