# generated by rudderc
# @name unknown
# @version unknown

bundle agent Configure_NTP_technique {

  vars:
    "resources_dir"        string => "${this.promise_dirname}/resources";
    "args"                  slist => {};
    "report_param"         string => join("_", args);
    "full_class_prefix"    string => canonify("Configure_NTP_technique_${report_param}");
    "class_prefix"         string => string_head("${full_class_prefix}", "1000");

  methods:
    # any:
    # 
    #   file("/tmp").absent()
    # 
    "${report_data.directive_id}_0"   usebundle => _method_reporting_context("any", "/tmp"),
                                             if => concat("ubuntu");
    "${report_data.directive_id}_0"   usebundle => file_absent("/tmp"),
                                             if => concat("ubuntu");
    "${report_data.directive_id}_0"   usebundle => _classes_noop(canonify("${class_prefix}_file_absent_/tmp")),
                                         unless => concat("ubuntu");
    "${report_data.directive_id}_0"   usebundle => log_rudder("Skipping method 'any' with key parameter '/tmp' since condition 'ubuntu' is not reached", "/tmp", canonify("${class_prefix}_file_absent_/tmp"), canonify("${class_prefix}_file_absent_/tmp"), @{args}),
                                         unless => concat("ubuntu");
    # any:
    # 
    #   file("/tmp").present()
    # 
    "${report_data.directive_id}_0"   usebundle => _method_reporting_context("any", "/tmp"),
                                             if => concat("debian");
    "${report_data.directive_id}_0"   usebundle => file_present("/tmp"),
                                             if => concat("debian");
    "${report_data.directive_id}_0"   usebundle => _classes_noop(canonify("${class_prefix}_file_present_/tmp")),
                                         unless => concat("debian");
    "${report_data.directive_id}_0"   usebundle => log_rudder("Skipping method 'any' with key parameter '/tmp' since condition 'debian' is not reached", "/tmp", canonify("${class_prefix}_file_present_/tmp"), canonify("${class_prefix}_file_present_/tmp"), @{args}),
                                         unless => concat("debian");
    "${report_data.directive_id}_0"   usebundle => log_rudder_mode("log_info", "ok", "None", "log_info");

}