# Create the list of all the base file to load to test
# It requires the NCF_TREE environment variable to be defined
bundle common ncf_inputs
{
  vars:
     "ncf_tree" string => getenv("NCF_TREE", 1024);

     # We could use find to build the full paths here, but that causes a very
     # long string to be built, causing CFEngine to error out, so we rebuild
     # the full paths using maplist below
     "generic_ncf_files"
        string => execresult("/bin/bash -c \"cd ${ncf_tree} && /usr/bin/find 10_ncf_internals/configuration.cf 20_cfe_basics 30_generic_methods 40_it_ops_knowledge -name '*.cf' -printf '%p\n'\"", "noshell");

     "default_files_relative" slist => splitstring("${generic_ncf_files}", "\n", 10000);
     "default_files"          slist => maplist("${ncf_tree}/${this}", default_files_relative);

}
