# Create the list of all the base file to load to test
# It requires the NCF_TREE environment variable to be defined
bundle common ncf_inputs
{
  vars:
     "ncf_tree" string => getenv("NCF_TREE", 1024);

     "generic_ncf_files"
        string => execresult("/bin/bash -c \"cd ${ncf_tree} && /usr/bin/find 20_cfe_basics 30_generic_methods 40_it_ops_knowledge -name '*.cf' -printf '${ncf_tree}/%p\n'\"", "noshell");

     "default_files"
        slist => splitstring("${generic_ncf_files}", "\n", 10000);

}
