
# Rudder-commons: API and utilities

This project is part of Rudder - IT infrastructure Automation and Compliance.
See: http://rudder.io for more information.

See repository main README for information about licensing, contribution, and
other general information.

== Synopsis

This project contains common API and utility classes used in other places.

It is composed of the following sub-projects:

* utils: utility classes, especially some classes for Hashcode of case classes, UUID generation, etc
* spring-run-dependencies: a Maven POM that defines common Spring dependencies used for runtime, like cglib or SLF4J bridge.
* historization-api: API for historization actions
* authorization-api: API for authorization checking
* eventlog-api: API for for logging events (user action, etc)

== Usage

This project is managed thanks to Maven software project management (http://maven.apache.org/).
You will have to have a working Maven (version 2.2.x or 3.0.x) installation.

.Clean, build and install on your local repository:
----
% mvn clean install
----


