#######################################################
#
# Sub cf file that simply generates abort
#
#######################################################

bundle common acc_path
{
  vars:
    "root" string => getenv("NCF_TESTS_ACCEPTANCE", 1024);
}

body common control
{
      inputs => { "${acc_path.root}/default.cf.sub", "${acc_path.root}/default_ncf.cf.sub", "@{ncf_inputs.default_files}" };
      bundlesequence  => { configuration, test };
      version => "1.0";
}

#######################################################

bundle agent test
{
  methods:
    "class" usebundle => _abort("reason", "message");
}

#######################################################

