# SPDX-License-Identifier: CC-BY-SA-2.0
# SPDX-FileCopyrightText: 2013-2020 Normation SAS
get:
  summary: List all global properties
  description: Get the current value of all the global properties (a.k.a. global parameters)
  operationId: listParameters
  responses:
    "200":
      description: Settings
      content:
        application/json:
          schema:
            type: object
            required:
              - result
              - action
              - data
            properties:
              result:
                type: string
                description: Result of the request
                enum:
                  - success
                  - error
              action:
                type: string
                description: The id of the action
                enum:
                  - listParameters
              data:
                type: object
                description: Parameters
                required:
                  - parameters
                properties:
                  parameters:
                    type: array
                    items:
                      $ref: ../../components/schemas/parameter.yml
  tags:
    - Parameters
  x-codeSamples:
    - lang: curl
      source:
        $ref: ../../code_samples/curl/parameters/list-parameters.sh
put:
  summary: Create a new property
  description: Create a new global property
  operationId: createParameter
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/parameter.yml
  responses:
    "200":
      description: Settings
      content:
        application/json:
          schema:
            type: object
            required:
              - result
              - action
              - data
              - id
            properties:
              id:
                type: string
                description: Id of the property
                example: rudder_file_edit_footer
              result:
                type: string
                description: Result of the request
                enum:
                  - success
                  - error
              action:
                type: string
                description: The id of the action
                enum:
                  - createParameter
              data:
                type: object
                description: Parameters
                required:
                  - parameters
                properties:
                  parameters:
                    type: array
                    items:
                      $ref: ../../components/schemas/parameter.yml
  tags:
    - Parameters
  x-codeSamples:
    - lang: curl
      source:
        $ref: ../../code_samples/curl/parameters/create-parameter.sh
