[package]
name = "rudder-module-inventory"
version = "0.0.0-dev"
description = "Minimal inventory agent generating Fusion Inventory compatible output"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
rudder_module_type = { path = "../../rudder-module-type" }
rudder_cli = { path = "../../rudder-cli" }
quick-xml = { version = "0.42.0", features = ["serialize"] }
sysinfo = "0.39"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tracing = { version = "0.1", features = ["max_level_trace", "release_max_level_trace"] }
clap = { version = "4.3.11", features = ["derive"] }
regex = "1"
jiff = "0.2.35"
nix = { version = "0.31", default-features = false, features = [
  "feature",
  "hostname",
  "user",
] }
wait-timeout = "0.2.1"

[dev-dependencies]
pretty_assertions = "1"
tempfile = "3"
