# generated by rudderc
# @name param_mult
# @version 1.0

function Param-Mult {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"bfe4005a-c854-4bea-a760-6343ee84bd5c"
  $common_params = @{
    ClassPrefix = "target"
    ComponentKey = "target"
    ComponentName = "File absent"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  if ($localContext.evaluate("linux")) {
    $call_params = @{
      Path = "target"
      PolicyMode = $PolicyMode
    }
    $call = File-Absent @call_params
    $compute_params = $common_params + @{
      MethodCall = $call
    }
    $context = Compute-Method-Call @compute_params
    $localContext.merge($context)
  }
  else {
    Rudder-Report-NA @common_params
  }
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"fa34708e-80c0-4369-b1b6-276d4f0a481a"
  $common_params = @{
    ClassPrefix = "openvpn"
    ComponentKey = "openvpn"
    ComponentName = "Package absent"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  Rudder-Report-NA @common_params
}
