#!/bin/sh

# Hooks parameter are passed by environment variable: 
#
# - RUDDER_GENERATION_DATETIME   : generation datetime: ISO-8601 YYYY-MM-ddTHH:mm:ss.sssZ date/time that identify that policy generation start 
# - RUDDER_NODE_ID               : the nodeId
# - RUDDER_NODE_HOSTNAME         : the node fully qualified hostname
# - RUDDER_NODE_POLICY_SERVER_ID : the node policy server id
# - RUDDER_AGENT_TYPE            : agent type ("cfengine-community", "cfengine-nova" or "dsc")
# - RUDDER_POLICIES_DIRECTORY_NEW: new policies directory (for ex for nodes under root: /var/rudder/share/$RUDDER_NODE_ID/rules.new)

# Correct all file permissions
/bin/chmod -R u-x,u+rwX,g-wx,g+rX,o-rwx "${RUDDER_POLICIES_DIRECTORY_NEW}"
r1=$?
/bin/chmod u-x,u+rwX,g-wx,g+rX,o-rwx "${RUDDER_POLICIES_DIRECTORY_NEW}/.."
r2=$?


# Root should not have the group changed
if [ "${RUDDER_NODE_ID}" != "root" ]; then
  /bin/chgrp -R rudder-policy-reader "${RUDDER_POLICIES_DIRECTORY_NEW}"
  r3=$?
  /bin/chgrp rudder-policy-reader "${RUDDER_POLICIES_DIRECTORY_NEW}/.."
  r4=$?
  # Return aggregated error code
  [ $r1 -eq 0 ] && [ $r2 -eq 0 ] && [ $r3 -eq 0 ] && [ $r4 -eq 0 ]
else
  # Return aggregated error code
  [ $r1 -eq 0 ] && [ $r2 -eq 0 ]
fi
