= policy-generation-node-ready

== When/What ?

This directory contains hooks executed after policies are fully
generated for node, but before these new policies replace the old
ones (technically, before we move /var/rudder/share/$NODEID/rules.new
to /var/rudder/share/$NODEID/rules).

Typically, these hooks proceed to sanity checks on the new policies
(ex: cf-promises), update permission on files, or interact with
external services using information from the generated policies
(ex: send node-properties JSON file to a third party service).

== Parameters

Hooks parameters are passed by environment variable:

- RUDDER_GENERATION_DATETIME   : generation datetime: ISO-8601
YYYY-MM-ddTHH:mm:ss.sssZ date/time that identify that policy generation start
- RUDDER_NODE_ID               : the nodeId
- RUDDER_NODE_HOSTNAME         : the node fully qualified hostname
- RUDDER_NODE_POLICY_SERVER_ID : the node policy server id
- RUDDER_AGENT_TYPE            : agent type ("cfengine-community" or "dsc")
- RUDDER_POLICIES_DIRECTORY_NEW: the full path of the base directory containing next policies for that node (during a
generation) (/var/rudder/share/$RUDDER_NODE_ID/rules.new/$RUDDER_AGENT_TYPE)

Technically, you could infer RUDDER_POLICIES_DIRECTORY_NEW, from RUDDER_NODE_ID, but it's tedious
for nodes behind a relay, and it is just simpler not to have to track what are the Rudder internal names,
which may change without notice.

