= policy-generation-node-finished

== When/What ?

This directory contains hooks executed after policies are fully
generated for node and made available for the node to download.

Typically, these hooks interact with external services using
knowledge from the generated policies  (ex: send node-properties
JSON file to a third party service).

== Parameters

Hooks parameters are passed by environment variable:

- RUDDER_GENERATION_DATETIME: generation datetime: ISO-8601 YYYY-MM-ddTHH:mm:ss.sssZ
date/time that identify that policy generation start
- RUDDER_NODEID             : the nodeId
- RUDDER_POLICIES_DIRECTORY : new policies directory (for ex for nodes
under root: /var/rudder/share/$RUDDER_NODEID/rules)
- RUDDER_AGENT_TYPE         : agent type ("cfengine-nova" or
"cfengine-community")

Technically, you could infer RUDDER_NEXT_POLICIES_DIRECTORY, from RUDDER_NODEID, but it's tedious
for nodes behind a relay, and it is just simpler not to have to track what are the Rudder internal names,
which may change without notice.
 
