# generated by rudderc
# @name Configure NTP
# @version 1.0

bundle agent Configure_NTP_technique {

  vars:
    "resources_dir"        string => "${this.promise_dirname}/resources";
    "args"                  slist => {};
    "report_param"         string => join("_", args);
    "full_class_prefix"    string => canonify("Configure_NTP_technique_${report_param}");
    "class_prefix"         string => string_head("${full_class_prefix}", "1000");

  methods:
    # Package present:
    # 
    #   package("ntp").present("","","") as package_present_ntp
    # 
    "${report_data.directive_id}_0"   usebundle => _method_reporting_context("Package present", "ntp");
    "${report_data.directive_id}_0"   usebundle => package_present("ntp", "", "", "");

}