# @generated by rudderc
# @name Configure NTP
# @version 1.0

bundle agent Configure_NTP_technique {
  vars:
    "resources_dir" string => "${this.promise_dirname}/resources";

  methods:
    "${report_data.directive_id}_0" usebundle => _method_reporting_context("Package present", "ntp");
    "${report_data.directive_id}_1" usebundle => package_present("ntp", "", "", "");
}