# generated by rudderc
# @name condition priority
# @version 1.0

function Condition-Priority {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"9903b8c8-1ae3-4bea-a77c-0d70553bd5ce"
  $common_params = @{
    ClassPrefix = "test"
    ComponentKey = "test"
    ComponentName = "Kernel module loaded"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  Rudder-Report-NA @common_params
}
