#!/bin/sh

set -e

case "$1" in
    supports-api-version)
        echo 1
        ;;
    get-package-data)
        while read line; do
            case "$line" in
                File=*)
                    echo PackageType=repo
                    echo Name=${line#File=}
                    ;;
                *)
                    true
                    ;;
            esac
        done
        ;;
    list-installed)
        while read line; do
            case "$line" in
                options=*)
                    OUTPUT=${line#options=}
                    ;;
                *)
                    exit 1
                    ;;
            esac
        done
        if [ -f "$OUTPUT" ]; then
            cat "$OUTPUT"
        fi
        ;;
    list-*)
        # Drain input.
        cat > /dev/null
        ;;
    repo-install)
        while read line; do
            case "$line" in
                options=*)
                    OUTPUT=${line#options=}
                    ;;
                Name=*)
                    NAME="${line#Name=}"
                    ;;
                Version=*)
                    VERSION="${line#Version=}"
                    ;;
                Architecture=*)
                    ARCHITECTURE="${line#Architecture=}"
                    ;;
                *)
                    exit 1
                    ;;
            esac
        done
        echo "Name=$NAME" >> "$OUTPUT"
        echo "Version=$VERSION" >> "$OUTPUT"
        echo "Architecture=$ARCHITECTURE" >> "$OUTPUT"
        ;;
    *)
        exit 1
        ;;
esac

exit 0
