#!/bin/sh

set -e

if [ `printf "%.1s" "$1"` = "-" ]
then
  # standard parsing
  while true
  do
    if [ "$1" = "--ncf-path" ]
    then
      framework_path="$2"
      shift 2
    else
      break
    fi
  done
fi

cd "${framework_path}"
for directory in "$@"
do
  # ignore directory if it doesn't exist
  if [ ! -d "${framework_path}/${directory}" ]; then continue; fi
  find "${directory}" -name '*.cf' -print
done
