#!/bin/sh

set -e

# Need at least 3 parameters
if [ "$#" -lt 3 ]
then
  echo "Usage $0 <CFEngine_version> <ncf_framework_path> <nn_directory> [<nn_directory ...]"
  echo "  Finds all *.cf files in <ncf_framework>/<nn_directory> that are compatible with the given CFEngine version"
  exit 1
fi

cfengine_version="$1"
framework_path="$2"
# see comment below on the last parameters
shift 2

_which() {
  name="$1"
  IFS_SAVE="$IFS"
  IFS=:
  for directory in $PATH
  do
    if [ -x "${directory}/${name}" ]
    then
      echo "${directory}/${name}"
      break
    fi
  done
  IFS="$IFS_SAVE"
}

# add busybox to path for android
PATH="/system/xbin:${PATH}"
# find commands
find_command=`_which find`
sed_command=`_which sed`
basename_command=`_which basename`
grep_command=`_which grep`
mkdir_command=`_which mkdir`
# stop if a command doesn't exist
[ ! -x "${find_command}" -o ! -x "${sed_command}" -o ! -x "${basename_command}" -o ! -x "${grep_command}" -o ! -x "${mkdir_command}" ] && echo "Posix commands not found" && exit 2

# split version numbers
version_regex='\([0-9]\+\)\.\([0-9]\+\).*'
cfengine_major=`echo -n ${cfengine_version} | ${sed_command} -e "s/${version_regex}/\\1/"`
cfengine_minor=`echo -n ${cfengine_version} | ${sed_command} -e "s/${version_regex}/\\2/"`

# Last parameters not named to keep them as a quoted array
for directory in "$@"
do
  if [ "${NCF_CACHE_PATH}" = "" ]
  then
    # maintain compatibility with old callers
    exclude_file="${framework_path}/${directory}/.ncf-exclude-cache-${cfengine_version}"
  else
    # take the cache directory from environment
    exclude_basedir="${NCF_CACHE_PATH}/ncf-exclude-cache-${cfengine_version}"
    [ -d "${exclude_basedir}" ] || ${mkdir_command} "${exclude_basedir}"
    canonified_path=`echo "${framework_path}/${directory}" | ${sed_command} -s "s/\\//_/g"`
    exclude_file="${exclude_basedir}/${canonified_path}"
  fi

  # ignore directory if it doesn't exist
  if [ ! -d "${framework_path}/${directory}" ]; then continue; fi

  # first remove obsolete cache for exclude list
  if [ -e "${exclude_file}" ]
  then
    newer_files=`${find_command} "${framework_path}/${directory}" -type f -newer "${exclude_file}"`
    if [ "${newer_files}" != "" ]
    then
      rm -f "${exclude_file}"
    fi
  fi

  # then create cache if it doesn't exist
  if [ -e "${exclude_file}" ]
  then
    excludes=`cat "${exclude_file}"`
  else
    # sed -ne '/regex/F' prints file name when regex matches
    tag_regex='^#[ \t]\+@agent_version[ \t]\+>='
    for file in `${find_command} "${framework_path}/${directory}" -name '*.cf' -exec ${grep_command} -l "${tag_regex}" '{}' \;`
    do
      major=`${sed_command} -ne "s/${tag_regex}${version_regex}/\\1/p" "${file}"`
      minor=`${sed_command} -ne "s/${tag_regex}${version_regex}/\\2/p" "${file}"`
      file_name=`${basename_command} ${file}`
      if [ "${major}" -gt "${cfengine_major}" ] || [ "${major}" -eq "${cfengine_major}" -a "${minor}" -gt "${cfengine_minor}" ]
      then
        # posix compliant syntax to exclude a file
        excludes="${excludes} -name ${file_name} -prune -o"
      fi

    done  
    echo -n "${excludes}" > "${exclude_file}"
  fi

  # eventually call find
  # posix compliant version of find without -printf '%p\n', it should work with darwin and aix
  ${find_command} "${framework_path}/${directory}" ${excludes} -name '*.cf' -print
done

