= policy-generation-node-finished

== When/What ?

This directory contains hooks executed after policies are fully
generated for node and made available for the node to download.

Typically, these hooks interact with external services using
knowledge from the generated policies  (ex: send node-properties
JSON file to a third party service).

== Parameters

Hooks parameters are passed by environment variable:

- RUDDER_GENERATION_DATETIME        : generation datetime: ISO-8601 YYYY-MM-ddTHH:mm:ss.sssZ
date/time that identify that policy generation start
- RUDDER_NODE_ID                    : the nodeId
- RUDDER_NODE_HOSTNAME              : the node fully qualified hostname
- RUDDER_NODE_POLICY_SERVER_ID      : the node policy server id
- RUDDER_AGENT_TYPE                 : agent type ("cfengine-community" or "dsc")
- RUDDER_POLICIES_DIRECTORY_CURRENT: the full path of the base directory containing policies for that node (for ex for
nodes under root: /var/rudder/share/$RUDDER_NODE_ID/rules/$RUDDER_AGENT_TYPE)

Technically, you could infer RUDDER_POLICIES_DIRECTORY_NEW, from RUDDER_NODE_ID, but it's tedious
for nodes behind a relay, and it is just simpler not to have to track what are the Rudder internal names,
which may change without notice.

