[package]
name = "rudder-module-augeas"
version = "0.0.0-dev"
description = "Configuration files management using Augeas"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-inline-default = "0.2"
rudder_module_type = { path = "../../rudder-module-type" }
raugeas = "0.2.2"

[dev-dependencies]
rudder_commons_test = { path = "../../rudder-commons-test" }
tempfile = "3"
