#!/bin/sh

# Hooks parameter are passed by environment variable: 
#
# - RUDDER_GENERATION_DATETIME    : generation datetime: ISO-8601 YYYY-MM-ddTHH:mm:ss.sssZ date/time that identify that policy generation start 
# - RUDDER_NODEID                 : the nodeId
# - RUDDER_NEXT_POLICIES_DIRECTORY: new policies directory (for ex for nodes under root: /var/rudder/share/$RUDDER_NODEID/rules.new)
# - RUDDER_AGENT_TYPE             : agent type ("cfengine-nova" or "cfengine-community")

# Correct all file permissions


/bin/chmod -R u-x,u+rwX,g-w,g+rx,o-rwx "${RUDDER_NEXT_POLICIES_DIRECTORY}"
r1=$?
/bin/chgrp -R rudder-policy-reader "${RUDDER_NEXT_POLICIES_DIRECTORY}"
r2=$?
/bin/chmod u-x,u+rwX,g-w,g+rx,o-rwx "${RUDDER_NEXT_POLICIES_DIRECTORY}/.."
r3=$?
/bin/chgrp rudder-policy-reader "${RUDDER_NEXT_POLICIES_DIRECTORY}/.."
r4=$?

# Return aggregated error code
[ $r1 -eq 0 ] && [ $r2 -eq 0 ] && [ $r3 -eq 0 ] && [ $r4 -eq 0 ]
