#!/bin/sh

# Hooks parameter are passed by environment variable: 
#
# - RUDDER_GENERATION_DATETIME    : generation datetime: ISO-8601 YYYY-MM-ddTHH:mm:ss.sssZ date/time that identify that policy generation start 
# - RUDDER_NODEID                 : the nodeId
# - RUDDER_NEXT_POLICIES_DIRECTORY: new policies directory (for ex for nodes under root: /var/rudder/share/$RUDDER_NODEID/rules.new)
# - RUDDER_AGENT_TYPE             : agent type ("cfengine-nova" or "cfengine-community")

if [ -z "${RUDDER_NEXT_POLICIES_DIRECTORY}" ]; then
  #bad rules.new directory
  echo "The directory for node ${RUDDER_NODEID} new policies is empty"
  exit 1;
else 
  case "${RUDDER_AGENT_TYPE}" in
    "windows-dsc")
      /usr/bin/zip -mr ${RUDDER_NEXT_POLICIES_DIRECTORY}/rudder.zip ${RUDDER_NEXT_POLICIES_DIRECTORY}/*
    ;;

    *)
      #do nothing for other agent type
      exit 0
    ;;
  esac
fi
