= policy-generation-node-ready

== When/What ?

This directory contains hooks executed after policies are fully
generated for node, but before these new policies replace the old
ones (technically, before we move /var/rudder/share/$NODEID/rules.new
to /var/rudder/share/$NODEID/rules).

Typically, these hooks proceed to sanity checks on the new policies
(ex: cf-promises), update permission on files, or interact with
external services using information from the generated policies
(ex: send node-properties JSON file to a third party service).

== Parameters

Hooks parameters are passed by environment variable:

- RUDDER_GENERATION_DATETIME    : generation datetime: ISO-8601
YYYY-MM-ddTHH:mm:ss.sssZ date/time that identify that policy generation start
- RUDDER_NODEID                 : the nodeId
- RUDDER_NEXT_POLICIES_DIRECTORY: new policies directory (for ex for nodes
under root: /var/rudder/share/$RUDDER_NODEID/rules.new)
- RUDDER_AGENT_TYPE             : agent type ("cfengine-nova" or
"cfengine-community")

Technically, you could infer RUDDER_NEXT_POLICIES_DIRECTORY, from RUDDER_NODEID, but it's tedious
for nodes behind a relay, and it is just simpler not to have to track what are the Rudder internal names,
which may change without notice.
 
