:imagesdir: images/

NOTE: This documentation has been written to the attention of _language_ contributors, or anyone would like to have an insight into _language_ source.

NOTE: _language_ is often abbreviated to *RL*

= rudderc

*rudderc* is a binary, standing for _rudder compiler_. +
It is _language_ (_.rd_ file format) compiler.
For now its purpose is to generate a configuration file (_CFEngine_, _DSC_, _JSON_...) from an RL file.

[align=center]
image::rudderc.svg[rudderc abilities]

== Commands

_rudderc_ has 4 commands that allow for different technique generations
- `compile`, its main purpose: take a _language_ technique and generate it in _CFEngine_ or _DSC_
- `save`, to generate a _language_ technique from its _JSON_ counterpart
- `technique read` (`read` is actually a subcommand) to convert a _language_ technique into its _JSON_ counterpart
- `technique generate` to take a _language_ technique and generate a _JSON_ object that contains the technique in all available formats (_JSON + CFEngine + DSC_)

[align=center]
image::rudderc.svg[rudderc commands]

=== Save command

[align=center]
image::save.svg[rudderc save command]

=== Compile command

[align=center]
image::compile.svg[rudderc compile command]

==== Compilation process part 1 - Parsing and abstract syntax tree creation 

image::compilation-command-1.svg[link="compilation-command-1.svg"]

==== Compilation process part 2 - Generation of output format from abstract syntax tree

Example taken from the CFEngine generator

image::compilation-command-2.svg[link="compilation-command-2.svg"]

== *stdlib*

What is called _stdlib_ (standing for _standard library_) is the following set of files, available in `./libs`:
- _resourcelib.rd_
Contains the list of methods (resources and their relative states and params) available to language users.
- _corelib.rd_
Contains standard enums available to language users.
- _oslib.rd_
Contains the exhaustive list of OSes available to language users.
- _cfengine_core.rd_
Contains the exhaustive list of CFEngine reserved words and namespaces that language users cannot create.

== Side tools (scripts)

=== generate_lib

A perl script that generates _resourcelib.rd_ by calling ncf api: _language_ generic methods library

[align=center]
image::generate-lib.svg[_language-lib generation]

=== generated_formats_tester

A python script that can either:

- compare two _json_ techniques and output unexpected differences
- compare two _cf_ techniques and output unexpected differences
- compare two _dsc_ techniques and output unexpected differences

It is designed to work in association with the main testing tool which is described in the next section

=== Full testing loop: tester.sh

It is the script called both from the production and dev (with a configuration file) environments.
See <<integration-testing-loop>> for explanations.

[[integration-testing-loop]]
== Integration testing loop

Right now _language_ is called for its own testing purpose to prepare a future complete integration: it is not yet used to generate techniques as code and does not yet totally replace the legacy generator.

In practice, every time a technique is saved from the _Technique Editor_, a script takes the 3 created files (_cf ps1 json_) and does the following:
    - generate _cf_ _ps1_ _json_ and _rl_ files by calling libraries and _rudderc_
    - compare the original files with _rudderc_ generated files by using the `generated_formats_tester` script
- differences and potential compilation / scripting errors are logged to `/var/log/rudder/language/${technique_name}/*`.

NOTE: diff comparison is custom as some differences are purposeful. Only unpurposeful differences (and errors) are logged.

Below is the full test loop:

image::test-loop.svg[test loop]

NOTE: Once log errors become rare enough _language_ will be released.

=== testing usage as a developer

When testing local techniques for example, here is the expected command: `./tools/tester.sh --dev --keep ./tests/techniques/condition_alias/technique`

NOTE: Notice how the file extension is not mentioned in the path, it is expected behavior, as the script only needs a valid path to the technique and its name. +
Also to work properly the script expects at least a _JSON_ and a _CFEngine_ techniques in order to compare original and generated files.

== Supported File formats

*rudderc* mostly deals with the following file formats, whether as input or output files:

- _JSON_ (_.json_)
- _language_ (_.rd_)
- _CFEngine_ (_.cf_)
- _DSC_ (_.cf_)

[align=center]
image::io-file-formats.svg[I/O file formats]

NOTE: Contribution process

Contribute by simply declaring a new issue here: https://issues.rudder.io/issues/

Contribute by fixing issues: 

* First, fork https://github.com/Normation/rudder
* Push your fix with the following commit name: `git commit -m "Fixes #{issue_id}: {branch name}"`
* Create a pull request to the right branch. Add the following PR comment: `+https://issues.rudder.io/issues/{issue_id}+`
