[#integration]
= Integration to Rudder

Right now language is in a _testing_ state. It has been released alongside _Rudder 7.0_.

This means while _language_ CLI features are usable, its current state as part of the released product is mainly: working in parallel with our legacy generation tools, to monitor how robust _language_ is and make sure it would not break things (and fix it when it would).

We made sure this integration is made flowlessly for the end user and does not come with any breaking change. More about the way we are integrating it in the next section (_Testing Loop_).

Once we ae confident enough with our new compiler, it will replace the actual generation process.

== Testing loop

Every time a technique is saved from the _Technique Editor_ (which outputs a _json_ _dsc_ and _cfengine_ technique), a script does the following:

- generate in a temporary folder _cf_ _json_ and _rd_ files by calling libraries and _rudderc_ compiler.
- compare the original files with _rudderc_ generated files.
- check and report (to `/var/log/rudder/language/${technique_id}/*`) differences and potential compilation or scripting errors.

== How to: disable automated usage of _language_ testing loop

While _rudderc_ is currently generating testing files only which means it's totally safe for the user, the parallel compilation can be disabled.

Open the following file: `/opt/rudder/etc/rudder-web.properties` and set `rudder.lang.test-loop.exec=true` to `false`.

_rudderc_ won't be called anymore until reactivation

== How to: manual testing

It is possible to directly take a look at the techniques generated via _language_, by calling the testing loop on your own for the _Rudder_ server command line.

The testing script location is `/opt/rudder/share/language/tools/tester.sh`. The script takes the following parameters:

- An *optional* `--keep` parameter that forces techniques generated via _language_ to be saved in a folder located in `/tmp` (a new folder is generated for every loop). The folder is actually echoed by the script so you can look at its content.
- The *mandatory*: technique name (actually the _Technique ID_, can be found in the _Technique Editor_)
- The *mandatory*: technique category under the form of a path. For example, default category is `ncf_techniques`.

The idea is that with those 2 mandatory parameters, the script can make up the technique correct path to the directory holding the technique: 
`/var/rudder/configuration-repository/techniques/${technique_category}/${technique_id}/1.0/`

Example:

To test the `new_tech` technique, located at: `/var/rudder/configuration-repository/techniques/systemSettings/networking/new_tech/1.0/technique(.cf)`

[source, bash]
----
$ /opt/rudder/share/language/tools/tester.sh --keep new_tech systemSettings/networking
  Done testing in /tmp/tmp.LFA6XjxkuF

$ ls -1 /tmp/tmp.LFA6XjxkuF                                                                                                                           [±ust_17738/add_doc_about_logs_and_generated_techniques ●]
new_tech.json                                   # generated by ncf
new_tech.cf                                     # generated by ncf (for now)
new_tech.ps1                                    # generated by ncf (for now)
new_tech.rd                                     # generated by rudderc --save
new_tech.rd.cf                                  # generated by rudderc --compile -f cf
new_tech.rd.ps1                                 # generated by rudderc --compile -f dsc

$ ls -1 /var/log/rudder/language/new_tech/   # generated logs for the technique testing loop (explicit names)
compare_json.log                                ### these logs hold any error or difference that is unexpected 
compare_cf.log                                  ### if no error / difference is found, the log file will not be generated 
compare_dsc.log                                 ### if no error / difference is found, the log file will not be generated 
rudderc.log                             
----
