[#statements]
= Statements

Statements are the atomic element of a state definition. It is an important concept that can be represented as:

* a state declaration: `resource().state() as mystatedecl` to store a state into a local variable that can be called
* a variable definition: `let mynamespace.myvar: OptionalType = "value"`. Variable can hold any supported type
* a variable extension: `mynamespace.myvar = value` to update value of an existing variable
* a (switch) `case`. cf <<case-conditions,case conditions>>
* an `if` condition, that contains an enum expression: `if expr => statement`. cf <<if-conditions,if conditions>>
* a flow statement: `return` `log_debug` `log_info` `log_warn` `fail` `noop`
Example of a state definition that exposes every statement type:

[source, language]
----
include::examples/statements.rd[]
----

[#if-conditions]
== `if` conditions

enum range or item access explained here <<access-enum-content,access to enum content>>

syntax:  `if expression => statement`

[#case-conditions]
== `case` conditions

Work the same way switch cases do in other languages

Syntax:
[source, language]
----
case {
  case_expression => statement,
  default => statement ## optional unless enum is global
}
----

`case` expressions are mostly standard expressions so they handle `&`, `|`, `!`, `(..)`, `default` the same way.
Only difference being `cases` have an additional `nodefault` expression that silently comes with a `noop` statement

[#expressions]
= Expressions

Expressions are composed of boolean expressions based on enum comparison +
Their purpose is to check whether the variable is of the right type and contains the provided item as a value, or an ancestor item if there is any
NOTE: `default` is a value that is equivalent of `true`

Expressions are a composition of the following elements:

* or: `expr | expr`
* and: `expr & expr`
* not: `!expr`
* parentheses: `(expr)` to handle priorities between expressions
* default: `default` keyword that automatically comes with a `noop` statement
* expression comparison:
** `var =~ enum` variable is equivalent to enum range or item
** `var !~ enum` variable is not equivalent to enum range or item
** implicit boolean comparison that only takes an expression (for example `!linux & !windows`)

NOTE: see enum related syntax <<access-enum-content,here>>, including items and range and expression examples

[#blocs]
= Blocks

Blocks are used to organize several state calls under a common statement or to modify their reporting logic.
They are exactly similar to the one found in Rudder, in the technique editor. They can be nested and are delimited by braces `{}` without keyword.

[source, language]
----
# Without any statement
@component = "My block component name"
@reporting_logic = "weighted"          ## Mandatory metadata for any block definition
{
  @component = "My method component name"
  command("""my command""").execution() as my_command_succeeds
}
----

[source, language]
----
# With statement
if gdm_present_ok =>                   ## The statement must be placed before the metadata
@component = "My block component name"
@reporting_logic = "weighted"          ## Mandatory metadata for any block definition
{
  @component = "My method component name"
  command("""my command""").execution() as my_command_succeeds
}
----

The `reporting_logic` metadata can take the following values:

* `weighted`: Keep the classical reporting
* `focus:<state id>`: The whole block reporting will take the compliance value of the selected state
** To choose the targeted state, add an `id` metadata to the state definition and reference its value instead of `<state id>`.
+
----
@component = "My block component name234"
@id = "90fbf043-11a8-49c6-85ad-88e65ea36f9a"
@reporting_logic = "focus:693e80c4-78f2-43c3-aace-3c6b5e0e08b8"
{
  @component = "My method component name"
  @id = "693e80c4-78f2-43c3-aace-3c6b5e0e08b8"
  command("""/bin/true""").execution() as command_execution__bin_true
}
----
* `worst-case-weighted-one`: The whole block reporting will take the compliance value of the worst report (will count as 1 report in the compliance computation)
* `worst-case-weighted-sum`: The whole block reporting will take the compliance value of the worst report, weighted by the number of methods (will count as N reports in the compliance computation, with N equals to the number of methods in the block)

