[#integration]
= Integration to Rudder

Right now rudder-lang is in an _alpha_ state. It is deployed but not properly released: _rudderc_ is already part of _Rudder_, but is not visible to the user.

What it means is neither available nor user techniques are generated using _rudder-lang_ yet.

== Testing loop

Yet _rudder-lang_ is in fact called, but only for its own testing purpose.

Every time a technique is saved from the _Technique Editor_ (which outputs a _cfengine_ technique), a script does the following using the generated technique:

- generates in a temporary folder _cf_ _json_ and _rl_ files by calling libraries and _rudderc_
- compares the original files with _rudderc_ generated files
- differences and potential compilation / scripting errors are logged to `/var/log/rudder/rudder-lang/${technique_id}/*`.

== How to: disable automated usage of _rudder-lang_ testing loop

Open the following file: `/opt/rudder/etc/rudder-web.properties` and set `rudder.lang.test-loop.exec=true` to `false`.

_rudderc_ won't be called anymore until reactivation

== How to: manual testing

It is possible to directly take a look at the techniques generated via _rudder-lang_, by calling the testing loop on your own for the _Rudder_ server command line.

The testing script location is `/opt/rudder/share/rudder-lang/tools/tester.sh`. The script takes the following parameters:

- An *optional* `--keep` parameter that forces techniques generated via _rudder-lang_ to be saved in a folder located in `/tmp` (a new folder is generated for every loop). The folder is actually echoed by the script so you can look at its content.
- The *mandatory*: technique name (actually the _Technique ID_, can be found in the _Technique Editor_)
- The *mandatory*: technique category under the form of a path. For example, default category is `ncf_techniques`.

The idea is that with those 2 mandatory parameters, the script can make up the technique correct path to the directory holding the technique: 
`/var/rudder/configuration-repository/techniques/${technique_category}/${technique_id}/1.0/`

Example:

To test the `new_tech` technique, located at: `/var/rudder/configuration-repository/techniques/systemSettings/networking/new_tech/1.0/technique(.cf)`

[source, bash]
----
$ /opt/rudder/share/rudder-lang/tools/tester.sh --keep new_tech systemSettings/networking
  Done testing in /tmp/tmp.LFA6XjxkuF

$ ls -1 /tmp/tmp.LFA6XjxkuF                                                                                                                           [±ust_17738/add_doc_about_logs_and_generated_techniques ●]
new_tech.json                                   # generated by ncf
new_tech.rl                                     # generated by rudderc --translate
new_tech.rl.cf                                  # generated by rudderc --compile
new_tech.rl.cf.json                             # generated by ncf (for now)

$ ls -1 /var/log/rudder/rudder-lang/new_tech/   # generated logs for the technique testing loop (explicit names)
compare_json.log                                ### these logs hold any error or difference that is unexpected 
compare_cf.log                                  ### if no error / difference is found, the log file will not be generated 
rudderc_compile.log                             
rudderc_translate.log                          
----
