There are two ways to interact with rudder-lang: directly from the terminal or through the Technique Editor

== Using the command line interface (CLI)

=== Installation

_rudder-lang_ program is called *rudderc*, standing for *Rudder Compiler*

To start working with _rudder-lang_, install a beta agent (see link:https://docs.rudder.io/history/6.1/reference/6.1/installation/agent/debian.html[rudder agent installation (debian)], other OSes guides available)

_rudderc_ being a part of the agent, it is now installed at the following location: `/opt/rudder/bin/rudderc`

Optionally add rudderc to your path `export PATH=$PATH:/opt/rudder/bin/rudderc` to simply run it with the following command: `rudderc`

=== Usage

`rudderc` has 4 features, called commands that will generate code. The command you need fully depend on the format you have and the output format you want:

* compile: generates either a DSC / CFEngine technique from a RudderLang technique
* save: generates a RudderLang technique from a JSON technique (same object format Technique Editor produces)
* technique read: generates a JSON technique (same object format Technique Editor produces) from a RudderLang technique
* technique generate: generates a JSON object that comes with RudderLang + DSC + CFEngine technique from a JSON technique
It is worth noting that `--stdin` and `--stdout` options are default behavior for `technique generate` and `technique read`

JSON output ( which includes logs) is handled. It is optional for compile and save but is default behavior for `technique read` and `technique generate`.
By default all logs but `error` are printed to `STDOUT`. `error` logs are printed to `STDERR`.

[align=center]
image::rudderc-simple.svg[rudderc abilities]

.The CLI usage (`rudderc --help` or `rudderc -h` output slightly modified)
----
Rudderc (4) available commands are callable through subcommands, namely <technique read>, <technique generate>, <save>, <compile>,
allowing it to perform generation or translation from / into the following formats : [JSON, RudderLang, CFengine, DSC].

Run `rudderc <SUBCOMMAND> --help` to access its inner options and flags helper

Example: rudderc technique generate -c confs/my.conf -i techniques/technique.json -f rudderlang

USAGE:
    rudderc <SUBCOMMAND>

FLAGS:
    -h, --help       
            Prints help information

    -V, --version    
            Prints version information


SUBCOMMANDS:
    compile      Generates either a DSC / CFEngine technique (`--format` option) from a RudderLang technique
    help         Prints this message or the help of the given subcommand(s)
    save      Generates a RudderLang technique from a JSON technique
    technique    A technique can either be used with one of the two following subcommands: `read` (from rudderlang
                 to json) or `generate` (from json to cfengine or dsc or rudderlang)
----
_rudderc_ *commands* all share several flags and options
.Shared FLAGS / OPTIONS:
----
FLAGS:
    -b, --backtrace    Generates a backtrace in case an error occurs
    -h, --help         Prints help information
        --stdin        Takes stdin as an input rather than using a file. Overwrites input file option
        --stdout       Takes stdout as an output rather than using a file. Overwrites output file option. Dismiss logs directed to stdout. Errors are kept since they are printed to stderr
    -V, --version      Prints version information

OPTIONS:
    -c, --config-file <config-file>    Path of the configuration file to use. A configuration file is required
                                       (containing at least stdlib and generic_methods paths) [default:
                                       /opt/rudder/etc/rudderc.conf]
    -i, --input <file>                 Input file path.
                                       If option path does not exist, concat config input with option.
    -l, --log-level <log-level>        rudderc output logs verbosity [default: warn]  [possible values: off, trace,
                                       debug, info, warn, error]
    -o, --output <file>                Output file path.
                                       If option path does not exist, concat config output with option. Else base output on input.
----

But some commands come with their own flags and options (listed below) on top of the previously mentioned:

.The first command, compile:
----
Generates a JSON object that comes with RudderLang + DSC + CFEngine technique from a JSON technique

USAGE:
    rudderc compile [FLAGS] [OPTIONS]

FLAGS:
    -j, --json-logs                     Use json logs instead of human readable output
                                        This option will print a single JSON object that will contain logs, errors and generated data (or the file where it has been generated).
                                        Whichever command is chosen, JSON output format is always the same.
                                        However, some fields (data and destination file) could be set to `null`, make sure to handle `null`s properly
                                        Note that NO_COLOR specs apply by default for json output.
                                        Also note that setting NO_COLOR manually in your env will also work

OPTIONS:
    -f, --format <format>              Enforce a compiler output format (overrides configuration format).
                                       [possible values: cf, cfengine, dsc, json]

...
----
.The second command, save:
----
Generates a RudderLang technique from a JSON technique

USAGE:
    rudderc save [FLAGS] [OPTIONS]

FLAGS:
    -j, --json-logs    Use json logs instead of human readable output
                       This option will print a single JSON object that will contain logs, errors and generated data (or the file where it has been generated).
                       Whichever command is chosen, JSON output format is always the same. However, some fields (data and destination file) could be set to `null`, make sure to handle `null`s properly
                       Note that NO_COLOR specs apply by default for json output.
                       Also note that setting NO_COLOR manually in your env will also work
----
.The third command, technique read (`read` is a subcommand of the `technique` subcommand):
----
Generates a JSON technique from a RudderLang technique

USAGE:
    rudderc technique read [FLAGS] [OPTIONS]

...
----
.The fourth command, technique generate (`generate` is a subcommand of the `technique` subcommand):
----
Generates a JSON object that comes with RudderLang + DSC + CFEngine technique from a JSON technique

USAGE:
    rudderc technique generate [FLAGS] [OPTIONS]

...
----


Most options are pretty straightforward but some explanations might help:

* Flags and options must be written in `kebab-case`
* A configuration file is required because _rudderc_ needs its own libraries to work (default path should point to an already working _Rudder_ configuration if _rudder agent_ was installed like previously suggested)
* Configuration can define flags and options but CLI will always overwrite config defined ones. ie: CLI `--output` > config `output`
* `--stdin` > `--input`
* `--stdout` > --output > `input` as destination with updated extension
* `--format` > `--output` technique extension
* `--log-levels` are ordered (trace > debug > info > warn > error) which means `info` includes `warn` and `error`
* `--stdin` is designed to work with pipes (ex: `cat file.rl` | rudderc compile -c file.conf -f cf`), it won't wait for an input. Higher priority than `--input` option
* `--stdout` will dismiss any kind of logs, including errors. Only thing that will be printed to terminal is the expected result. If empty, try again with a log, there is an error. Higher priority than `--output` option

==== Options: how are input, output and format dealt with:

Internally for input the compiler looks for an existing file until it founds one, in the following order:
* solely from the CLI input option
* join configuration input as dir + CLI input option
* solely from the configuration input (if the file exists)
* if none worked, error

Internally for output, the compiler looks for an existing path to write a file on, until it founds one:
* solely from the CLI output option
* join configuration output as dir + CLI output option
* solely from the configuration output
* uses input and only updates the extension 
* if none worked, error

Internally for format when required (`compile`):
* for any command but `compile`, format is set by the program 
* compile command: explicit CLI `--format` option. Note that values are limited. 
* compile command: output file extension is used
* if none worked, error


==== Configuration file

A configuration file is required because _rudderc_ needs its own libraries to work.

Entire _rudder-lang_ environment is already set up alongside the agent: this includes all needed libraries and a configuration file with preset paths.

.default configuration file
[source,toml]
----
[shared]
stdlib="libs/"
cfengine_methods="repos/ncf/tree/30_generic_methods/"
alt_cfengine_methods="repos/dsc/plugin/ncf/30_generic_methods/"
dsc_methods="repos/dsc/packaging/Files/share/initial-policy/ncf/30_generic_methods/"

[compile]
input="tests/techniques/simplest/technique.rl"
output="tests/techniques/simplest/technique.rl.cf"

[save]
input="tests/techniques/simplest/technique.cf"
output="tests/techniques/simplest/technique.cf.rl"

[technique_read]
input="tests/techniques/simplest/technique.rl"
output="tests/techniques/simplest/technique.rl.json"

[technique_generate]
input="tests/techniques/simplest/technique.json"
output="tests/techniques/simplest/technique_array.json"

[testing_loop]
cfengine="/opt/rudder/bin/cf-promises"
ncf_tools="repos/ncf/tools/"
py_modules="tools/"


----

The configuration file can be used to shorten arguments.

There is a table for each command (`compile`, `technique_read`, `technique_generate`, `save`), that can hold their own two limited fields: `input` and `output`.
Meaningful usage is that these two fields are paths that are completed by CLI filenames: `--input <file>` / `--output <file>` CLI options.
In other words: config options are paths (directories), to which is joined the cli option.
But configure it using a file and not use the CLI options will work.

==== Compilation examples

Below, 5 ways to use the compiler

===== Required: a config file to work on a local environment: 

.tools/my.conf
[source,toml]
----
[shared]
stdlib="libs/"
cfengine_methods="repos/ncf/tree/30_generic_methods/"
alt_cfengine_methods="repos/dsc/plugin/ncf/30_generic_methods/"
dsc_methods="repos/dsc/packaging/Files/share/initial-policy/ncf/30_generic_methods/"
----

===== CLI full version
----
rudderc compile --json-log --log-level debug --config-file tools/my.conf --input tests/techniques/technique.rl --output tests/techniques/technique.rl.dsc --format dsc
----

===== CLI shortened version
----
rudderc compile -j -l debug -c tools/my.conf -i tests/techniques/technique.rl -f dsc
----

What it means:

* Compiles `tests/techniques/technique.rl` (`-i`) into `tests/techniques/technique.rl.dsc` (output based on input),
* Use the configuration file located at `./tools/my.conf` (`-c`),
* Output technique format is DSC (`--format`). Note that this parameter is optional since `-d` defines the right technique format by its extension
* Output log format is JSON (`-j`),
* The following log levels: error, warn, info, debug will be printed to the terminal

===== CLI + config shortened version

By using an adapted configuration file, it can be simplified:

.tools/myconf
[source,toml]
----
[shared]
    stdlib="libs/" # only required field for rudderc

[compile]
    input="tests/techniques/"
    output="tests/techniques/"
----

Lightest compilation using CLI.
----
rudderc -j -l debug -c tools/myconf -i technique.rl
----

Input will be a concatenation of config and cli: `tests/techniques/technique.rl`. Output still based on input.

===== config + CLI shortest version

By using an adapted configuration file, it can be simplified:

.tools/myconf
[source,toml]
----
[shared]
    stdlib="libs/" # only required field for rudderc

[compile]
    input="rl/technique.rl"
    output="dsc/technique.rl.dsc"
----

Lightest compilation using CLI.
----
rudderc -j -l debug -c tools/myconf
----

==== JSON Output

If you decided to go with the `--json-output` option, it means output will consist of a single JSON object:

.STDOUT
[source,json]
----
{
  "command": "compile",
  "time": "1600331631367",
  "status": "success",
  "source": "tests/techniques/simplest/technique.rl",
  "logs": [],
  "data": [
    {
      "format": "DSC",
      "destination": "tests/techniques/6.1.rc5/technique.dsc",
      "content": null
    }
  ],
  "errors": []
}
----

* Output always use the same squeleton which is the one you just read.
* `data` field:
** Length always 0 in case of error # TODO check for technique generate
** Length always 3 when `technique generate called`
** Length always 1 in any other case since other commands only generate 1 format
* `content` field is null if its content has succesfully been written to a file
* `destination` field is null if content is directly written in the JSON
* `errors` field is an array of strings
# TODO log field

== Using the Technique Editor

Since _rudder-lang_ has not been released yet, it is accessible from the _6.1_ beta version (and later)

_RL_ is called from the _Technique Editor_ as a backend program every time a technique is saved. For now it only is a testing loop. Once fully released, every technique will directly be saved using _rudder-lang_

NOTE: This testing loop generates two _CFEngine_ techniques, one using the usual _ncf_ framework and an other one using _rudder-lang_. The two are then compared.

Since the Technique Editor is meant to simplify methods generation no _rudder-lang_ code is written (the language is fully abstracted). It is used as an internal _CFEngine_ generator
