There are two ways to interact with rudder-lang: directly from the terminal or through the Technique Editor

== Using the command line interface (CLI)

=== Installation

_rudder-lang_ program is called *rudderc*, standing for *Rudder Compiler*

To start working with _rudder-lang_, install a beta agent (see link:https://docs.rudder.io/history/6.1/reference/6.1/installation/agent/debian.html[rudder agent installation (debian)], other OSes guides available)

_rudderc_ being a part of the agent, it is now installed at the following location: `/opt/rudder/bin/rudderc`

Optionally add rudderc to your path `export PATH=$PATH:/opt/rudder/bin/rudderc` to simply run it with the following command: `rudderc`

=== Usage

`rudderc` has 2 features:

* Compile which is the default behavior: takes a _RL_ technique as an input and generates the desired 
* Translate which is the alternative mode:  takes a _JSON_ technique as an input and generates a _rudder-lang_ technique (_.rl_) 

Any information log is displayed to `SDTOUT`, errors should be printed to `STDERR`

[align=center]
image::rudderc-simple.svg[rudderc abilities]

.The CLI usage (`rudderc --help` or `rudderc -h` output slightly modified)
----
USAGE:
    rudderc [FLAGS] [OPTIONS]

FLAGS:
    -h, --help         Prints help information
    -j, --json-log     Use json logs instead of human readable output
    -t, --translate    Use technique translation mode rather than default compilation mode
    -V, --version      Prints version information

OPTIONS:
    -c, --config-file <config-file>
            Path of the configuration file to use.
            A configuration file is required (containing at least stdlib path)
            [default: /opt/rudder/etc/rudderc.conf]

    -f, --format <format>
            Enforce a compiler output format (overrides configuration format and manual technique extension)
            [possible values: cf, dsc, json]

    -l, --log-level <log-level>
            rudderc output logs verbosity
            [default: warn]
            [possible values: off, trace, debug, info, warn, error]

    -s, --source <source>
            Input file path. Overwrites base input

    -n, --technique-name <technique-name>
            Technique name to use for both input (if no input provided) and output (if no output or provided), based on configuration file paths

    -d, --dest <dest>
            Output file path, overrides config and technique-name.
            If neither an output nor a configuration file output path is set, source path is used

    -o, --output-technique-name <output-technique-name>
            Technique name to use for output (if no output provided), based on configuration file path
----

Most options are pretty straightforward but some explanations might help:

* Flags and options must be written in `kebab-case`
* A configuration file is required because _rudderc_ needs its own libraries to work (default path should point to an already working _Rudder_ configuration if _rudder agent_ was installed like previously suggested)
* Unlike the prevailing `--source` (`-s`) and `--dest` (`-d`) options, the `--technique-name <technique joined>` (`-n`) and `--technique-output-name <technique joined>` (`-o`) options makes use of the configuration file input and output paths and concatenates the `<technique joined>` to these
* `--source` > configuration source + `--technique-name` > configuration source if it is a file
* `--dest` > configuration dest + `--technique-name` (`-n`) > configuration dest if it is a file > `--source` as destination with updated format
* `--format` (`-f`) > configuration format > `--dest` technique extension
* Log levels are ordered (trace > debug > info > warn > error)

==== Configuration file

A configuration file is required because _rudderc_ needs its own libraries to work.

Entire _rudder-lang_ environment is already set up alongside the agent: this includes all needed libraries and a configuration file with preset paths.

.default configuration file
[source,toml]
----
[shared]
    stdlib="libs/" # only required field for rudderc --compile
    ncf_generic_methods="/usr/share/ncf/tree/30_generic_methods/"
    dsc_generic_methods="/var/rudder/configuration-repository/dsc/ncf/30_generic_methods/"

[compile]
    source="./tests/test_files/tester/"
    dest="./tests/test_files/tester/"
    # format="dsc"

[translate]
    source="tests/test_files/tester/"
    dest="tests/test_files/tester/"
    # format="dsc" # format here will just be ignored as translate can only generate rudder-lang

[testing_loop]
    cfengine="/opt/rudder/bin/cf-promises"
    ncf_tools="/usr/share/ncf/tools/"
    py_modules="tools/"
----

The configuration file can be used to shorten arguments.

The `source` and `dest` fields from both `[translate]` and `[compile]` can either be filled with a path or a file.

===== Configuration file set with directories

[source,toml]
----
...

[compile]
    source="rl/"
    dest="cf/"
----

Paths will respectively be prepended to _rudderc_ `-n` and `-o` options

===== Configuration file set with files

Paths will be used as they are, since they already define a single technique.

Note that `-n` and `-o` _rudderc_ options will use the config specified directories and only override technique name

==== Compilation example

1. Required: a config file to work on a local environment: 

.tools/myconf
[source,toml]
----
[shared]
    stdlib="libs/" # only required field for rudderc --compile
----

2. CLI full version
----
rudderc --json-log --log-level debug --config-file tools/myconf --source rl/technique.rl --dest dsc/technique.rl.dsc --format dsc
----

3. CLI shortened version
----
rudderc -j -l debug -c tools/myconf -n technique.rl -o technique.rl.dsc -f dsc
----

What it means:

* Compile is the default behavior, therefore it has no dedicated option.
* Compiles `./rl/technique.rl` (`-s`) into `./dsc/technique.rl.dsc` (`-d`),
* Use the configuration file located at `./tools/myconf` (`-c`),
* Output technique format is DSC (`--format`). Note that this parameter is optional since `-d` defines the right technique format by its extension
* Output log format is JSON (`-j`),
* The following log levels: error, warn, info, debug will be printed to the terminal

4. CLI + config shortened version

By using an adapted configuration file, it can be simplified:

.tools/myconf
[source,toml]
----
[shared]
    stdlib="libs/" # only required field for rudderc

[compile]
    source="rl/technique.rl"
    dest="dsc/technique.rl.dsc"
    format="dsc"
----

Lightest compilation using CLI.
----
rudderc -j -l debug -c tools/myconf
---- 

Or using `rl` and `dsc` directories with other techniques:
----
rudderc -j -l debug -c tools/myconf -n another.rl -o another_from_rl.rl.dsc
---- 

==== Translation example

1. Required: a config file to work on a local environment: 
.tools/myconf
[source,toml]
----
[shared]
    stdlib="libs/" # only required field for rudderc --compile
----

2. CLI full version
----
rudderc --json-log --log-level debug --config-file tools/myconf --translate --source json/technique.json --dest rl/from_json.rl
----

3. CLI shortened version
----
rudderc -tj -l debug -c tools/myconf -s technique.json -d rl/from_json.rl
----

What it means:
- Translate (`-t`) `./json/technique.json` (`-s`) into `./rl/from_json.rl` (`-d`),
- Use the configuration file located at `./tools/myconf` (`-c`),
- Output log format is JSON (`-j`),
- The following log levels: error, warn will be printed to the terminal

4. CLI + config lightened version

By using an adapted configuration file, it can be simplified:

.tools/myconf
[source,toml]
----
[shared]
    stdlib="libs/" # only required field for rudderc

[translate]
    source="json/technique.json"
    dest="rl/from_json.rl"
----

Lightest translation using CLI.
----
rudderc -tj -l warn -c tools/myconf
---- 

Or using `json` and `rl` directories with other techniques:
----
rudderc -tj -l warn -c tools/myconf -n another.json -o another_from_json.rl
---- 

== Using the Technique Editor

Since _rudder-lang_ has not been released yet, it is accessible from the _6.1_ beta version (and later)

_RL_ is called from the _Technique Editor_ as a backend program every time a technique is saved. For now it only is a testing loop. Once fully released, every technique will directly be saved using _rudder-lang_

NOTE: This testing loop generates two _CFEngine_ techniques, one using the usual _ncf_ framework and an other one using _rudder-lang_. The two are then compared.

Since the Technique Editor is meant to simplify methods generation no _rudder-lang_ code is written (the language is fully abstracted). It is used as an internal _CFEngine_ generator
