[resolver]
# Allow security and important fixes to override the police
#incompatible-publish-age = "allow"


[registry]
# For now use with "cargo +nightly -Zmin-publish-age update"
#global-min-publish-age = "7 days"
