# generated by rudderc
# @name cdt
# @version 1.0

function Cdt {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"ee867477-8629-448f-85d5-c8ef33357c0f"
  $common_params = @{
    ClassPrefix = "tmp"
    ComponentKey = "tmp"
    ComponentName = "File absent"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  if ($localContext.evaluate("debian")) {
    $call_params = @{
      Path = "tmp"
      PolicyMode = $PolicyMode
    }
    $call = File-Absent @call_params
    $compute_params = $common_params + @{
      MethodCall = $call
    }
    $context = Compute-Method-Call @compute_params
    $localContext.merge($context)
  }
  else {
    Rudder-Report-NA @common_params
  }
}
