@Library('slack-notification')
import org.gradiant.jenkins.slack.SlackNotifier

pipeline {
    agent none
    triggers { cron('@daily') }
    stages {

        stage('methods') {
            agent {
                dockerfile {
                    filename 'ci/methods.Dockerfile'
                    // Run tests as root
                    args  "--user 0"
                    additionalBuildArgs "--build-arg OS=ubuntu:20.04"
                }
            }
            steps {
                catchError {
                    sh script: 'PATH="/opt/rudder/bin:$PATH" make test-unsafe', label: 'test methods'
                }
                // clean leftover files owned by root anyway
                sh script: 'rm -rf tests/acceptance/.succeeded', label: 'cleanup'
                sh script: 'rm -rf tests/acceptance/.failed', label: 'cleanup'
                sh script: 'rm -rf tests/acceptance/workdir', label: 'cleanup'
            }
            post {
                failure {
                    script {
                        new SlackNotifier().notifyResult("shell-team")
                    }
                }

            }
        }
        stage("Compatibility tests") {
            // Expensive tests only done daily on branches
            when {
                allOf {
                    triggeredBy 'TimerTrigger'
                    not { changeRequest() }
                }
            }
            matrix {
                axes {
                    axis {
                        name 'OS'
                        values 'debian:11'
                    }
                }
                stages {
                    stage('methods') {
                        agent {
                            dockerfile {
                                filename 'ci/methods.Dockerfile'
                                // Run tests as root
                                args  "--user 0"
                                additionalBuildArgs "--build-arg OS=${OS}"
                            }
                        }
                        steps {
                            catchError {
                                sh script: 'PATH="/opt/rudder/bin:$PATH" make test', label: 'test methods'
                            }
                            // clean leftover files owned by root anyway
                            sh script: 'rm -rf tests/acceptance/.succeeded', label: 'cleanup'
                            sh script: 'rm -rf tests/acceptance/.failed', label: 'cleanup'
                            sh script: 'rm -rf tests/acceptance/workdir', label: 'cleanup'
                        }
                        post {
                            failure {
                                script {
                                    new SlackNotifier().notifyResult("shell-team")
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('End') {
            steps {
                echo 'End of build'
            }
            post {
                fixed {
                    script {
                        new SlackNotifier().notifyResult("shell-team")
                    }
                }
            } 
        }
    }
}
