
# cargo-vet audits file

[[audits.boon]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "0.5.0 -> 0.5.1"

[[audits.colored]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "2.0.0 -> 2.0.4"

[[audits.cpufeatures]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "0.2.7 -> 0.2.8"

[[audits.errno]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "0.3.1 -> 0.3.2"

[[audits.errno]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "0.3.2 -> 0.3.3"

[[audits.format_serde_error]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
version = "0.3.0"

[[audits.format_serde_error]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "0.3.0 -> 0.3.1@git:06ef275ce1f2c56b91fa0a4785e28c3aa9c67b31"

[[audits.hermit-abi]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "0.3.1 -> 0.3.2"

[[audits.iana-time-zone]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "0.1.56 -> 0.1.57"

[[audits.mdbook]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "0.4.30 -> 0.4.32"

[[audits.memoffset]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
version = "0.6.5"

[[audits.nu-ansi-term]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
version = "0.46.0"

[[audits.overload]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
version = "0.1.1"

[[audits.pretty_assertions]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "1.3.0 -> 1.4.0"

[[audits.static_assertions]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
version = "1.1.0"

[[audits.tempfile]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "3.5.0 -> 3.6.0"

[[audits.tempfile]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "3.6.0 -> 3.7.0"

[[audits.tempfile]]
who = "Alexis Mousset <alexis.mousset@rudder.io>"
criteria = "safe-to-deploy"
delta = "3.7.0 -> 3.8.0"

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2024-06-27"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-16"
end = "2024-06-27"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2024-06-27"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2024-06-27"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2024-06-27"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2024-06-27"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2024-08-03"

[[trusted.assert_cmd]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2019-03-23"
end = "2024-06-27"

[[trusted.basic-toml]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2023-01-25"
end = "2024-06-27"

[[trusted.bitflags]]
criteria = "safe-to-deploy"
user-id = 3204 # Ashley Mannix (KodrAus)
start = "2019-05-02"
end = "2024-08-30"

[[trusted.bstr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-04-02"
end = "2024-06-27"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-01"
end = "2024-06-27"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 4357 # Thom Chiovoloni (thomcc)
start = "2023-08-02"
end = "2024-08-03"

[[trusted.chrono]]
criteria = "safe-to-deploy"
user-id = 4556 # Dirkjan Ochtman (djc)
start = "2022-07-25"
end = "2024-06-09"

[[trusted.clap]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2024-06-27"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-28"
end = "2024-06-27"

[[trusted.clap_complete]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-31"
end = "2024-06-27"

[[trusted.clap_derive]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2024-06-27"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-04-15"
end = "2024-06-27"

[[trusted.cpufeatures]]
criteria = "safe-to-deploy"
user-id = 5059 # Artyom Pavlov (newpavlov)
start = "2022-08-18"
end = "2024-08-03"

[[trusted.either]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2019-04-02"
end = "2024-08-03"

[[trusted.env_logger]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-11-24"
end = "2024-06-27"

[[trusted.equivalent]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2023-02-05"
end = "2024-06-27"

[[trusted.fastrand]]
criteria = "safe-to-deploy"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2021-04-24"
end = "2024-08-03"

[[trusted.form_urlencoded]]
criteria = "safe-to-deploy"
user-id = 72883 # Valentin Gosu (valenting)
start = "2022-09-08"
end = "2024-06-27"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2024-06-27"

[[trusted.indexmap]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2020-01-15"
end = "2024-06-27"

[[trusted.is-terminal]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2022-01-22"
end = "2024-08-03"

[[trusted.itoa]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2024-06-27"

[[trusted.js-sys]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-06-27"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-29"
end = "2024-06-27"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2021-01-27"
end = "2024-06-27"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2020-03-17"
end = "2024-06-27"

[[trusted.libm]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-05-14"
end = "2024-06-27"

[[trusted.libm]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2022-02-06"
end = "2024-06-27"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2024-08-03"

[[trusted.lock_api]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2024-06-27"

[[trusted.log]]
criteria = "safe-to-deploy"
user-id = 3204 # Ashley Mannix (KodrAus)
start = "2019-07-10"
end = "2024-08-30"

[[trusted.mdbook]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2023-08-04"
end = "2024-08-30"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2024-06-27"

[[trusted.mime]]
criteria = "safe-to-deploy"
user-id = 359 # Sean McArthur (seanmonstar)
start = "2019-09-09"
end = "2024-08-30"

[[trusted.minijinja]]
criteria = "safe-to-deploy"
user-id = 39 # Armin Ronacher (mitsuhiko)
start = "2021-09-23"
end = "2024-06-09"

[[trusted.nix]]
criteria = "safe-to-deploy"
user-id = 6094 # Alan Somers (asomers)
start = "2019-05-22"
end = "2024-08-30"

[[trusted.num-traits]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2019-05-20"
end = "2024-08-03"

[[trusted.parking_lot]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2024-06-27"

[[trusted.parking_lot_core]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2024-06-27"

[[trusted.percent-encoding]]
criteria = "safe-to-deploy"
user-id = 72883 # Valentin Gosu (valenting)
start = "2022-09-08"
end = "2024-06-27"

[[trusted.pest]]
criteria = "safe-to-deploy"
user-id = 95892 # Tomas Tauber (tomtau)
start = "2022-07-29"
end = "2024-06-27"

[[trusted.pest_derive]]
criteria = "safe-to-deploy"
user-id = 95892 # Tomas Tauber (tomtau)
start = "2022-07-29"
end = "2024-06-27"

[[trusted.pest_generator]]
criteria = "safe-to-deploy"
user-id = 95892 # Tomas Tauber (tomtau)
start = "2022-07-29"
end = "2024-06-27"

[[trusted.pest_meta]]
criteria = "safe-to-deploy"
user-id = 95892 # Tomas Tauber (tomtau)
start = "2022-07-29"
end = "2024-06-27"

[[trusted.phf]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-06-17"
end = "2024-06-27"

[[trusted.phf_codegen]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-06-17"
end = "2024-06-27"

[[trusted.phf_generator]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-06-17"
end = "2024-06-27"

[[trusted.phf_shared]]
criteria = "safe-to-deploy"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-06-17"
end = "2024-06-27"

[[trusted.pin-project-lite]]
criteria = "safe-to-deploy"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2019-10-22"
end = "2024-08-01"

[[trusted.predicates]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2019-04-22"
end = "2024-06-27"

[[trusted.predicates-core]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2020-12-29"
end = "2024-06-27"

[[trusted.predicates-tree]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2020-12-29"
end = "2024-06-27"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2024-06-27"

[[trusted.quick-xml]]
criteria = "safe-to-deploy"
user-id = 2927 # Mingun
start = "2022-05-25"
end = "2024-06-27"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2024-06-27"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2024-06-27"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2024-06-27"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2024-06-27"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2024-06-27"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2024-06-27"

[[trusted.same-file]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-16"
end = "2024-06-27"

[[trusted.scopeguard]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2020-02-16"
end = "2024-06-27"

[[trusted.serde]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-06-27"

[[trusted.serde_derive]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-06-27"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2024-06-27"

[[trusted.serde_spanned]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-01-20"
end = "2024-08-03"

[[trusted.serde_yaml]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2024-06-27"

[[trusted.sha2]]
criteria = "safe-to-deploy"
user-id = 5059 # Artyom Pavlov (newpavlov)
start = "2020-01-06"
end = "2024-06-27"

[[trusted.sharded-slab]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-10-02"
end = "2024-08-01"

[[trusted.siphasher]]
criteria = "safe-to-deploy"
user-id = 468 # Frank Denis (jedisct1)
start = "2019-09-20"
end = "2024-08-30"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2024-08-03"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-06-27"

[[trusted.termcolor]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-04"
end = "2024-06-27"

[[trusted.termtree]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-10-07"
end = "2024-06-27"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2024-08-03"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2024-08-03"

[[trusted.thread_local]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-09-07"
end = "2024-08-01"

[[trusted.toml]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-05-16"
end = "2024-06-27"

[[trusted.toml]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-12-14"
end = "2024-08-03"

[[trusted.toml_edit]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-09-13"
end = "2024-08-03"

[[trusted.tracing]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-06-28"
end = "2024-08-01"

[[trusted.tracing-attributes]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-08-08"
end = "2024-08-01"

[[trusted.tracing-core]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-06-20"
end = "2024-08-01"

[[trusted.tracing-log]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-06-27"
end = "2024-08-01"

[[trusted.tracing-serde]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-06-27"
end = "2024-08-01"

[[trusted.tracing-subscriber]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-06-27"
end = "2024-08-01"

[[trusted.ucd-trie]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-21"
end = "2024-06-27"

[[trusted.unicase]]
criteria = "safe-to-deploy"
user-id = 359 # Sean McArthur (seanmonstar)
start = "2019-03-05"
end = "2024-08-30"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2024-08-03"

[[trusted.unsafe-libyaml]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2022-07-03"
end = "2024-06-27"

[[trusted.url]]
criteria = "safe-to-deploy"
user-id = 72883 # Valentin Gosu (valenting)
start = "2020-01-09"
end = "2024-06-27"

[[trusted.uuid]]
criteria = "safe-to-deploy"
user-id = 3204 # Ashley Mannix (KodrAus)
start = "2019-10-18"
end = "2024-07-19"

[[trusted.walkdir]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-09"
end = "2024-06-27"

[[trusted.wasi]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2020-06-03"
end = "2024-06-27"

[[trusted.wasm-bindgen]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-06-27"

[[trusted.wasm-bindgen-backend]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-06-27"

[[trusted.wasm-bindgen-macro]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-06-27"

[[trusted.wasm-bindgen-macro-support]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-06-27"

[[trusted.wasm-bindgen-shared]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-06-27"

[[trusted.winapi-util]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2020-01-11"
end = "2024-06-27"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2024-06-22"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2024-06-22"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2024-06-22"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2024-06-22"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2024-06-22"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2024-06-22"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2024-06-22"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2024-06-22"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2024-06-22"

[[trusted.winnow]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-02-22"
end = "2024-08-03"
