#!/usr/bin/python3

"""
Cf and Json / language compatibility tester
Usage:
    generated_formats_tester compare-json [--config-file=<local_config_path.conf>] <first.json> <new.json>
    generated_formats_tester compare-cf [--config-file=<local_config_path.conf>] <first.cf> <new.cf>
    generated_formats_tester compare-dsc [--config-file=<local_config_path.conf>] <first.dsc> <new.dsc>
"""

import sys
import os
import configparser
import codecs
import json
from pprint import pprint
import re
from subprocess import check_output

aliases = dict()

def load_condition_aliases(oslib_file):
  try:
    with open(oslib_file, "r") as lib:
      lines = lib.readlines()
      for i, line in enumerate(lines):
        inner_content = re.match(r'\s*\@cfengine_name\s*=\s*\[\s*([\w\",\s]*)\s*\]', line)
        if inner_content:
          aliases_list = re.findall(r'\"(\w+)\"', inner_content.groups()[0])
          # get reference name. Does not work in case of multiline alias metadata
          reference = re.match(r'\s*(\w*),?\s*', lines[i + 1])
          if reference:
            aliases.setdefault(reference.groups()[0], []).extend(aliases_list)
          else:
            print("WARNING: Reference of alias metadata is not formatted as expected, see:", aliases_list)
        else:
          alias = re.match(r'\s*enum\s*alias\s*(\w+)\s*=\s*(\w+)\s*', line)
          if alias:
            aliases.setdefault(alias.groups()[1], []).append(alias.groups()[0])
  except IOError as e:
    print_json("load oslib file", "oslib", str(e), True)
    exit(1)

# prints the output at json format. If no issue : nothing is printed. Else, print either json diff or python error
def print_json(function, filename, json_to_format, is_python_error=False):
  if is_python_error:
    formatted_json = { "function": function, "file": filename, "diff": json_to_format }
  else:
    formatted_json = { "function": function, "file": filename,  "error": json_to_format }
  print(json.dumps(formatted_json, indent=2) + ',')

# for now ignore all `condition` parenthesis differences, priorities should be handled correctly from within the program
# depends (TE builtin condition type vs any.(manually written condition))
# eventually check condition equivalence
def filter_condition(diff_values):
  # remove all parenthesis
  generated_filtered = ''.join(filter(lambda c: c not in ['(', ')'], diff_values[1]))
  original_filtered = ''.join(filter(lambda c: c not in ['(', ')'], diff_values[0]))
  if original_filtered == 'any.' + generated_filtered or original_filtered == generated_filtered:
    return True
  # condition should also be valid if the only diffs are alias replacements
  else:
    original_condition_arr = list(filter(lambda c: c not in ['any', ''], re.findall(r'(\w+)*', original_filtered)))
    generated_condition_arr = list(filter(lambda c: c not in [''], re.findall(r'(\w+)*', generated_filtered)))
    for o, g in zip(original_condition_arr, generated_condition_arr):
      if g not in aliases or o not in aliases[g]:
        return False
    return True


def compare_json(first, second):
  try:
    with open(first, "r") as f1:
      try:
        with open(second, "r") as f2:
          j1 = json.load(f1)
          j2 = json.load(f2)
      except IOError as e:
        print_json("compare_json", second, str(e), True)
        exit(1)
  except IOError as e:
    print_json("compare_json", first, str(e), True)
    exit(1)
  diff = jsondiff.diff(j1, j2, syntax="symmetric", marshal=True)
  # del as this field just does not exist on <Rudder6 versions json
  deep_del(diff, ['calls', 'parameters', '$insert'], '$$errors', lambda d: True)
  deep_del(diff, ['$insert'], 'resources', lambda d: len(d['resources']) == 0)
  deep_del(diff, ['$delete'], 'resources', lambda d: len(d['resources']) == 0)
  deep_del(diff, ['calls'], 'condition', lambda d: filter_condition(d['condition']))
  # for now generated lib has no method specific resource parameter so it will take default resource parameter
  deep_del(diff, ['calls', 'parameters'], 'name', lambda d: True)
  empty_dict_cleaner(diff)
  # print if diff
  if len(diff) != 0:
    print_json("compare_json", second, diff)
    exit(1)


def load_cf(filename):
  # Check file exists
  if not os.path.exists(filename):
    filename = "{}/{}".format(os.getcwd(), filename)
    if not os.path.exists(filename):
      print_json("compare_cf", filename, 'No such file', True)
      exit(1)

  env = os.environ.copy()
  env['RES_OPTIONS'] = 'attempts:0'
  try:
    # CFEngine reauires explicitly either a ./ or ab absolute path
    if filename.startswith("/"):
      out = check_output([ncf.CFENGINE_PATH, "-pjson", "-f", filename], env=env)
    else:
      out = check_output([ncf.CFENGINE_PATH, "-pjson", "-f", "./", filename], env=env)
    promises = json.loads(out)
  except Exception as e:
    print_json("compare_cf", filename, 'An error occurred while parsing cf technique: {}'.format(str(e)), True)
    exit(1)
  return promises

def compare_cf(first, second):
  j1 = load_cf(first)
  j2 = load_cf(second)
  diff = jsondiff.diff(j1, j2, syntax="symmetric", marshal=True)
  remove_wilful_entries_cf(first, diff)
  empty_dict_cleaner(diff)
  if diff and len(diff) != 0:
    print_json("compare_cf", second, diff)
    exit(1)

# returns a list of lines cleaned from comments and useless whitespaces
def load_dsc(filename):
  # Check file exists
  if not os.path.exists(filename):
    if not filename.startswith("/"):
      filename = "{}/{}".format(os.getcwd(), filename)

    if not os.path.exists(filename):
      print_json("compare_dsc", filename, 'No such file', True)
      exit(1)
  # read file
  f = open(filename, "r")
  # clean file
  is_powershell_string = False
  is_block_comment = False
  purged_content = []
  original = []
  line_index = 0
  for line in f:
    purged_line = ""
    original_line = ""
    last_char=''
    line_index += 1
    for char in line:
      if char == '#' and last_char == '<' and is_powershell_string is False:
        is_block_comment = True
      elif char == '>' and last_char == '#' and is_powershell_string is False:
        is_block_comment = False
      if is_block_comment is True or (char.isspace() and last_char.isspace()):
        last_char = char
        continue
      elif char == '#' and is_powershell_string is False:
        last_char = char
        break
      elif char == "'" or char == '"':
        is_powershell_string != is_powershell_string
      elif char == "{" and last_char == "$": # ie is interpolated within a string
        is_powershell_string != is_powershell_string
      elif char == "}" and last_char != "\\": # ie is interpolated within a string
        is_powershell_string != is_powershell_string

      if not is_powershell_string:
        purged_line += char_cleaner(char)
      else:
        purged_line += char
      original_line += char
      last_char = char
    # remove mob special char
    purged_line = purged_line.replace(u'\ufeff', "")
    # remove starting/ending whitespaces
    purged_line = purged_line.strip().replace("(", "").replace(")", "")
    if len(purged_line):
      original.append({ 'content': original_line, 'line': line_index })
      # TODO put this somewhere else, in a proper updated function
      # split in two lines (diff)
      condition = re.search('\$class = "any\.(?P<condition>.+)"', purged_line)
      if condition and condition.group('condition'):
        purged_content.append('$class = "{}"'.format(condition.group('condition')))
      elif purged_line == "} else {":
        purged_content.append("}")
        purged_content.append("else {")
        original.append({ 'content': purged_line, 'line': line_index }) # line added 2 times to compensate for the added line to purged_content
      else:
        purged_content.append(purged_line)
    last_char = char
  return (original, purged_content)

# casefold make the char is lowercase, spaces, '_' and '-' are removed
# since powershell rules are not restrictives, these differences does not matter
def char_cleaner(char):
  return char.casefold().replace('-', '').replace('_', '')

def get_diffs_dsc(base_original, base_purged_content, generated_original, generated_purged_content, generated_filename):
  diff = list()
  for (index, base_purged_line) in enumerate(base_purged_content):
    try:
      if base_purged_line != generated_purged_content[index] \
        and base_purged_line.replace(" {", "technique {") != generated_purged_content[index]:
        diff.append({ "expected": base_original[index], "generated": generated_original[index] })
    except:
      print_json("compare_dsc", generated_filename, 'Part of generated DSC content is wrong, probably missing', True)
      exit(1)
  return diff

def compare_dsc(original_filename, generated_filename):
  (base_original, base_purged) = load_dsc(original_filename)
  (generated_original, generated_purged) = load_dsc(generated_filename)
  diff = get_diffs_dsc(base_original, base_purged, generated_original, generated_purged, generated_filename)
  if diff and len(diff) != 0:
    print_json("compare_dsc", generated_filename, diff)
    exit(1)

# recursively deletes empty entries. Is considered empty an empty object or an object that only holds a 'line' key
def empty_dict_cleaner(diff_dict):
  istodel=False
  if type(diff_dict) is dict:
    for elem in diff_dict.copy():
      cur = diff_dict[elem]
      istodel |= empty_dict_cleaner(cur)
      if type(cur) is dict:
        if len(cur) == 0 or (type(cur) is dict and len(cur) == 1 and 'line' in cur.keys()):
          istodel = True
        else:
          istodel = False
        if istodel:
          diff_dict.pop(elem)
  elif type(diff_dict) is list:
    for elem in diff_dict.copy():
      istodel |= empty_dict_cleaner(elem)
  elif type(diff_dict) is tuple:
    for elem in diff_dict:
      istodel |= empty_dict_cleaner(elem)
  return istodel


# deletes from diff list every i/o difference done on purpose (ie that are not a bug)
def remove_wilful_entries_cf(file_name, diff):
  # try:
    promises_path = ['bundles', 'promiseTypes', 'contexts', 'promises']
    # del name since `_technique` is always added
    deep_del(diff, ['bundles'], 'name', lambda d: len(d['name']) == 2 and d['name'][0] + '_technique' == d['name'][1])
    # del sourcePath since it is not relevant
    deep_del(diff, ['bundles'], 'sourcePath', lambda d: 'sourcePath' in d)
    # del lines that add vars on purpose when generating cfengine from language
    delete_vars_insertions = lambda d: del_from_array(d['$insert'], [], 'promiser', ['args', 'report_param', 'full_class_prefix', 'class_prefix'])
    deep_del(diff, promises_path, '$insert', delete_vars_insertions)
    # del superfluous if->true equivalent condition
    is_if_any = lambda d: d['lval'] == 'if' and d['rval']['arguments'][0]['value'] == 'any'
    deep_del(diff, promises_path + ['attributes', '$delete'], '$delete', is_if_any)

    # Technique Editor does not handle the na_log if method call condition is for windows
    deep_del(diff, promises_path + ['attributes', 'rval'], 'rval', lambda d: 'log_na_rudder' in d['name'])
    # Note: cannot check that the generated cf technique should indeed be a na_log
    # silence deleted condition error since conditions have no place next to na_logs
    deep_del(diff, promises_path + ['attributes'], '$delete', lambda d: d['lval'] == 'if')

    # del priority and 'any.' starting conditions
    deep_del(diff, promises_path + ['attributes', 'rval', 'arguments'], 'value', lambda d: filter_condition(d['value']))
    # del lines that add log_rudder and _classes_noop
    del_method_insertions = lambda d: del_from_array(d['$insert'], ['attributes', 'rval'], 'name', ['log_rudder', '_classes_noop'])
    deep_del(diff, promises_path, '$insert', del_method_insertions)
  # except Exception as e:
  #   print_json("compare_cf", file_name, 'An error occurred while cleaning cf diffs: {}'.format(str(e)), True)
  #   exit(1)

def del_from_array(obj, deep_list, needle, values, deletion_offset=0):
  for index, elem in enumerate(obj.copy()):
    if get_if_contains(elem, deep_list, needle, values):
      obj.pop(index - deletion_offset)
      deletion_offset += 1
  if len(obj) == 0:
    return True
  return False

# always wrap deletion conditions in a try-exception in case obj format is not what expected
def try_del_condition(f, obj):
  try:
    return f(obj)
  except:
    return False
# Deletes haystack content from delfrom key, if needle (and values) match deep_list keys
# IMPORTANT when delfrom is an array:
  # 1. check from del_condition whether the whole object can be deleted (there could be unexpected values in it)
  # 2. delete each inner element in del_condition - so that if the array is not deleted, expected values will
  # del_from_array function solves this issue
# this
# USAGE
  # deep_del({bundle: { name: 'test' }, ['bundle'], 'bundle', lambda d: d['name'] == 'test')
  # will match name = 'test' in bundle, and delete parent entries up to 'bundle'
  # OTOH deep_del({not_bundle: { name: 'test' }, ['bundle'], 'bundle', lambda d: d['name'] == 'test')
  # will not match list path and will not delete anything
# EXAMPLE + note:
  # note that the following example works fine even with the missing path, but there is a lot more chances we match another '$insert'
  # deep_del(diff, ['$insert'], '$insert', delete_purposeful_insertions)
  # deep_del(diff, ['bundles', 'promiseTypes', 'contexts', 'promises', '$insert'], '$insert', delete_purposeful_insertions)
# ARGUMENTS
  # haystack: object to look into
  # deep_list (array of string): ordered list of keys to search from
  # delfrom: delfrom any self/parent of the matched needle (if matched)
  # del_condition (function): check if elem matches deletion condition
  # index is an internal counter
def deep_del(haystack, deep_list, delfrom, del_condition, index=0):
  istodel = False
  # 1: get in dict, if content matches searched keys
  if type(haystack) is dict:
    if len(deep_list) == index and try_del_condition(del_condition, haystack):
      istodel = True
    elif index < len(deep_list) and deep_list[index] in haystack:
      istodel |= deep_del(haystack[deep_list[index]], deep_list, delfrom, del_condition, index + 1)
    # else go deeper to find next deep_list element / needle
    else:
      for _, value in haystack.items():
        istodel |= deep_del(value, deep_list, delfrom, del_condition, index)
    if istodel and delfrom in haystack:
      haystack.pop(delfrom)
      return False
  # 2: get inner content until dict
  elif type(haystack) is list or type(haystack) is tuple:
    for elem in haystack:
      istodel |= deep_del(elem, deep_list, delfrom, del_condition, index)
  return istodel

# Currently not used, but could be useful
# checks if a key values pair exists in a given path (and returns the value found)
# optionally takes an array of expected values, if no values given: returns first match
# USAGE
  # see deep del, similar behavior but returns the matched value rather than deleting a part of the dict
# ARGUMENTS
  # haystack: object to look into
  # deep_list (array of string): ordered list of keys to search from
  # needle (string): the final key to look for within deep_list matched object
  # values (optional, array of string): match if needle value is contained in this array
  # index is an internal counter
def get_if_contains(haystack, deep_list, needle, values=None, index=0):
  if type(haystack) is dict:
    # if len not eq -> match path is wrong
    if len(deep_list) == index and needle in haystack and (values is None or haystack[needle] in values):
      return haystack[needle]
    elif index < len(deep_list) and deep_list[index] in haystack:
      return get_if_contains(haystack[deep_list[index]], deep_list, needle, values, index + 1)
    # this part is important: out of index but allows to iterate on last elements which should include needle
    for _, value in haystack.items():
      ret = get_if_contains(value, deep_list, needle, values, index)
      if ret is not None:
        return ret # else keep iterating
  elif type(haystack) is list or type(haystack) is tuple:
    for elem in haystack:
      ret = get_if_contains(elem, deep_list, needle, values, index)
      if ret is not None:
        return ret # else keep iterating
  return None

def load_config():
  cfg = configparser.ConfigParser()
  cfgpath='/opt/rudder/etc/rudderc.conf'
  if os.path.exists(cfgpath):
    cfg.read(cfgpath)
    python_modules_dir = cfg['testing_loop']['py_modules'].strip('\"')
    sys.path.append(python_modules_dir)
  return cfg

if __name__ == "__main__":
  try:
    cfg = load_config()
    import docopt
    import jsondiff
    arguments = docopt.docopt(__doc__)
    if arguments['--config-file']:
      cfg.read(arguments['--config-file'])
    ncf_tools = cfg['testing_loop']['ncf_tools'].strip('\"')
    cfengine_path = cfg['testing_loop']['cfengine'].strip('\"')
    load_condition_aliases(cfg['shared']['stdlib'].strip('\"') + 'oslib.rd')
  except Exception as e:
    print_json('(Not defined yet)', '(Not defined yet)', 'An error occurred while setting config up: {}'.format(str(e)), True)
    exit(1)

  try:
    sys.path.append(ncf_tools)
    import ncf
    ncf.CFENGINE_PATH=cfengine_path
  except Exception as e:
    print_json('(Not defined yet)', '(Not defined yet)', 'An error occurred while importing ncf: {}'.format(str(e)), True)
    exit(1)

  if arguments['compare-json']:
    compare_json(arguments['<first.json>'], arguments['<new.json>'])
  elif arguments['compare-cf']:
    compare_cf(arguments['<first.cf>'], arguments['<new.cf>'])
  elif arguments['compare-dsc']:
    compare_dsc(arguments['<first.dsc>'], arguments['<new.dsc>'])
