#!/bin/bash

set -e

FIRST_INSTALL="$1"
APACHE="$2"
APACHE_USER="$3"
APACHE_GROUP="$4"
APACHE_VHOSTDIR="$5"

LOG_FILE="/var/log/rudder/install/rudder-server-relay-$(date +%Y%m%d%H%M%S).log"

echo "$(date) - Starting rudder-server-relay post installation script" >> ${LOG_FILE}

# Create groups ans users before managing the services
echo -n "INFO: Creating users ..."
if ! getent group rudder > /dev/null; then
  groupadd --system rudder >> ${LOG_FILE}
fi

if ! getent group rudder-policy-reader > /dev/null; then
  groupadd --system rudder-policy-reader >> ${LOG_FILE}
  usermod -a -G rudder-policy-reader "${APACHE_USER}" >> ${LOG_FILE}
fi

if ! getent passwd rudder-relayd >/dev/null; then
  useradd --system --shell /bin/false --gid rudder --home-dir /var/rudder --comment "Rudder relayd,,," rudder-relayd >> ${LOG_FILE}
fi

if ! getent passwd rudder >/dev/null; then
  useradd --system --shell /bin/false --gid rudder --home-dir /var/rudder --comment "Rudder,,," rudder >> ${LOG_FILE}
fi
echo " Done"

# Always reload systemd (in case we changed the unit file)
echo -n "INFO: Configuring systemd services..."
systemctl daemon-reload >> ${LOG_FILE}
if [ "${FIRST_INSTALL}" -eq 1 ]; then
  systemctl enable rudder-relayd >> ${LOG_FILE}
fi

systemctl stop "${APACHE}" >> ${LOG_FILE} || true

systemctl stop rudder-relayd >> ${LOG_FILE} || true
echo " Done"

# share directory with rudder-policy-reader
chgrp -R rudder-policy-reader /var/rudder/share
chmod 750 /var/rudder/share
find /var/rudder/share -type d | xargs chmod g+s-w

# change some directory to rudder owner
chown rudder: /var/rudder/shared-files
chmod 770 /var/rudder/shared-files
chmod 755 /var/rudder/inventories

for dir in /var/rudder/inventories/incoming /var/rudder/inventories/accepted-nodes-updates /var/rudder/reports/incoming /var/rudder/reports/failed
do
  chmod 770 ${dir}
  chown ${APACHE_USER}:rudder ${dir}
done

# Setup password files for inventory reception WebDAV access
for passwdfile in /opt/rudder/etc/htpasswd-webdav-initial /opt/rudder/etc/htpasswd-webdav
do
  htpasswd -bc ${passwdfile} rudder rudder >> ${LOG_FILE}
done

# Generate certificates if needed
if [ ! -f /opt/rudder/etc/ssl/rudder.crt ] || [ ! -f /opt/rudder/etc/ssl/rudder.key ]; then
  echo -n "INFO: No usable SSL certificate detected for Rudder relay HTTPS support, generating one automatically..."
  SUBJALTNAME=DNS:$(hostname --fqdn) openssl req -new -x509 -newkey rsa:2048 -subj "/C=FR/ST=France/L=Paris/CN=$(hostname --fqdn)/emailAddress=root@$(hostname --fqdn)/" -keyout /opt/rudder/etc/ssl/rudder.key -out /opt/rudder/etc/ssl/rudder.crt -days 1460 -nodes -sha256 -config /opt/rudder/etc/ssl/openssl.cnf -extensions server_cert >/dev/null
  chgrp ${APACHE_GROUP} /opt/rudder/etc/ssl/rudder.key && chmod 640 /opt/rudder/etc/ssl/rudder.key
  echo " Done"
fi

# put this certificate in ca.cert if it doesn't exist (we need at least on certificate there)
if [ ! -f /opt/rudder/etc/ssl/ca.cert ]; then
  cp /opt/rudder/etc/ssl/rudder.crt /opt/rudder/etc/ssl/ca.cert
fi

if [ ! -f /var/rudder/lib/ssl/nodescerts.pem ]; then
  touch /var/rudder/lib/ssl/nodescerts.pem
  touch /var/rudder/lib/ssl/allnodescerts.pem
fi

# Remove wsgi conf from vhost
sed -i '/^Set up a WSGI serving process/d' /etc/${APACHE_VHOSTDIR}/rudder.conf
sed -i '/^WSGI/d' /etc/${APACHE_VHOSTDIR}/rudder.conf

echo -n "INFO: Starting services..."
systemctl start rudder-relayd >> ${LOG_FILE}
systemctl start "${APACHE}" >> ${LOG_FILE}
echo " Done"

echo "INFO: rudder-server-relay setup complete."
# Only output this notice during initial installation
if [ "${FIRST_INSTALL}" -eq 1 ]; then
  uuid_file="/opt/rudder/etc/uuid.hive"
  if [ -f "${uuid_file}" ]; then
    uuid=$(cat ${uuid_file})
    if [ "${uuid}" != "root" ]; then
      echo ""
      echo "*****************************************************************************************"
      echo "INFO: Now run on your root server:                                                             "
      echo "INFO:   '/opt/rudder/bin/rudder-node-to-relay ${uuid}"
      echo "INFO: Please look at the documentation for details (Section 'Relay servers')           "
      echo "*****************************************************************************************"
    fi
  else # if for some reason there is no uuid here (should not happen)
    echo ""
    echo "*****************************************************************************************"
    echo "INFO: * If you are installing a root server, configuration is automatically done         "
    echo "INFO: * If you are installing a simple relay, run:                                       "
    echo "INFO:   '/opt/rudder/bin/rudder-node-to-relay <your uuid>'          "
    echo "INFO:   on your root server to complete this node transition to a relay server.          "
    echo "INFO:   Please look at the documentation for details (Section 'Relay servers')           "
    echo "*****************************************************************************************"
  fi
fi

echo "$(date) - Ending rudder-server-relay post installation script" >> ${LOG_FILE}

