# generated by rudderc
# @name parameters
# @version 1.0

function Parameters {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Parameter(Mandatory=$True)]
    [String]$Paramtest,
    [Switch]$AuditOnly
  )

  $LocalClasses = New-ClassContext
  $ResourcesDir = $PSScriptRoot + "\resources"
  _rudder_common_report_na -ComponentName "Package absent" -ComponentKey "${paramtest}" -Message "Not applicable" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly
}
