# generated by rudderc
# @name 6_2_cis_updated
# @version 1.0

function 6-2-Cis-Updated {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Parameter(Mandatory=$True)]
    [String]$Module,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+""
  $common_params = @{
    ClassPrefix = "skip_item_${report_data.canonified_directive_id}"
    ComponentKey = "skip_item_${report_data.canonified_directive_id}"
    ComponentName = "Condition from variable existence"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  $call_params = @{
    Condition = "skip_item_${report_data.canonified_directive_id}"
    PolicyMode = $PolicyMode
    VariableName = "node.properties[skip][${report_data.directive_id}]"
  }
  $call = Condition-From-Variable-Existence @call_params
  $compute_params = $common_params + @{
    MethodCall = $call
  }
  $context = Compute-Method-Call @compute_params
  $localContext.merge($context)
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"70d2759a-b3f8-43ca-a515-f005a9be651a"
  $common_params = @{
    ClassPrefix = "${module}"
    ComponentKey = "${module}"
    ComponentName = "Kernel module configuration"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  Rudder-Report-NA @common_params
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"449625c9-30a4-4b1a-8e88-f854fe67a108"
  $common_params = @{
    ClassPrefix = "${module}"
    ComponentKey = "${module}"
    ComponentName = "Kernel module not loaded"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  Rudder-Report-NA @common_params
}
