# generated by rudderc
# @name supported_formats
# @version 1.0

function Supported-Formats {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Switch]$AuditOnly
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $LocalClasses = New-ClassContext
  $ResourcesDir = $PSScriptRoot + "\resources"
  $ReportId = $ReportIdBase+"929a286e-1fc0-4147-876e-5a009f162822"
  _rudder_common_report_na -ComponentName "Condition once" -ComponentKey "cfengine_only" -Message "Not applicable" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly
  $ReportId = $ReportIdBase+"65a6abf0-52cc-47d3-a3d0-6470bca49734"
  $LocalClasses = Merge-ClassContext $LocalClasses $(Directory-Present -Path "shared_cf_dsc" -ComponentName "Directory present" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly).get_item("classes")
  $ReportId = $ReportIdBase+"2c88bb01-9178-4aa0-87b0-cbcbda5c8a71"
  $Class = "windows"
  if (Evaluate-Class $Class $LocalClasses $SystemClasses) {
    $LocalClasses = Merge-ClassContext $LocalClasses $(Directory-Present -Path "shared_cf_dsc_condition" -ComponentName "Directory present" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly).get_item("classes")
  }
  else {
    _rudder_common_report_na -ComponentName "Directory present" -ComponentKey "shared_cf_dsc_condition" -Message "Not applicable" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly
  }
  $ReportId = $ReportIdBase+"062332fb-2b49-4386-8cfe-46dad2dbe92d"
  $LocalClasses = Merge-ClassContext $LocalClasses $(Registry-Key-Present -Key "DSC_ONLY" -ComponentName "Registry key present" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly).get_item("classes")
  $ReportId = $ReportIdBase+"37a1055d-ee98-4b56-81a0-562134476acc"
  $Class = "windows"
  if (Evaluate-Class $Class $LocalClasses $SystemClasses) {
    $LocalClasses = Merge-ClassContext $LocalClasses $(Registry-Key-Present -Key "IF_DSC_ONLY" -ComponentName "Registry key present" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly).get_item("classes")
  }
  else {
    _rudder_common_report_na -ComponentName "Registry key present" -ComponentKey "IF_DSC_ONLY" -Message "Not applicable" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly
  }
}
