# generated by rudderc
# Generated from json technique
@format = 0
@name = "technique with blocks"
@description = ""
@version = "1.0"
@category = "ncf_techniques"
@parameters = []

resource technique_technique_with_blocks()

technique_technique_with_blocks state technique() {
  @component = "First block"
@id = "341e4fd0-e900-4ae4-947c-ecd164b1744a"
@reporting_logic = "sum"
{
    @component = "File absent"
  @id = "6077d281-ebd7-432f-bdcc-d377431f0ecc"
  file("""/tmp/block1""").absent() as file_absent__tmp_block1
  @component = "inner block"
@id = "73a5de0e-a4a7-41aa-aa97-2daa193d9f44"
@reporting_logic = "sum"
{
    @component = "File absent"
  @id = "0f6032bd-0735-419c-90db-ae434f47e1fd"
  file("""/tmp/block1_1""").absent() as file_absent__tmp_block1_1
    @component = "Command execution"
  @id = "d9313380-26b2-469a-83d1-734f568d6a5a"
  command("""/bin/true""").execution() as command_execution__bin_true
  }
  }

    @component = "Command execution"
  @id = "9ca0e832-7ea9-435e-add0-46b792244698"
  command("""/bin/true #root1""").execution() as command_execution__bin_true__root1

    @component = "File absent"
  @id = "eec2c63b-8811-4ea0-93b9-334ee54baea3"
  file("""/tmp/root2""").absent() as file_absent__tmp_root2
}
