# generated by rudderc
# @name Configure NTP
# @version 1.0

function Configure-NTP-Technique {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$False)] [Switch] $AuditOnly,
    [Parameter(Mandatory=$True)]  [String] $ReportId,
    [Parameter(Mandatory=$True)]  [String] $TechniqueName
  )

  $LocalClasses = New-ClassContext
  $ResourcesDir = $PSScriptRoot + "\resources"

  _rudder_common_report_na -ComponentName "Package-Present" -ComponentKey "Version" -Message "Not-Applicable" -ReportId $ReportId -AuditOnly $AuditOnly -TechniqueName $TechniqueName

}