= node-post-deletion

== When/What ?

This directory contains hooks executed after a node was successfully deleted.

Typically, these hooks clean resources related to that node and
notify external services that the node was deleted from Rudder.

== Parameters

Hooks parameters are passed by environment variable:

- RUDDER_NODE_ID: the nodeId
- RUDDER_NODE_HOSTNAME: the node fully qualified hostname
- RUDDER_NODE_POLICY_SERVER_ID: the node policy server id
- RUDDER_AGENT_TYPE : agent type ("cfengine-community" or "dsc")
- RUDDER_POLICIES_DIRECTORY_CURRENT: the full path of the base directory containing policies for that node (for ex for
nodes under root: /var/rudder/share/$RUDDER_NODE_ID/rules/$RUDDER_AGENT_TYPE)
- RUDDER_POLICIES_DIRECTORY_NEW    : the full path of the base directory containing next policies for that node (during
a generation) (/var/rudder/share/$RUDDER_NODE_ID/rules.new/$RUDDER_AGENT_TYPE)
- RUDDER_POLICIES_DIRECTORY_ARCHIVE: the full path of the base directory containing previous policies for that node
- RUDDER_NODE_KIND: node kind: root, relay or node


