# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2020 Normation SAS

install:
	cd rudderc && make install

docs:
	cd rudderc && make docs

check:
	cd rudderc && make check
	cd rudder-resource-type && make check
	cd rudder-commons && make check

