#!/bin/sh

# Hooks parameter are passed by environment variable:
#
# - RUDDER_NODE_ID: the nodeId
# - RUDDER_NODE_HOSTNAME: the node fully qualified hostname
# - RUDDER_NODE_POLICY_SERVER_ID: the node policy server id
# - RUDDER_NODE_OS_NAME: OS normalized name (Linux distribution, Windows with version, etc)
# - RUDDER_NODE_OS_VERSION: OS version
# - RUDDER_NODE_OS_SP: OS service pach
# - RUDDER_NODE_OS_STRING: OS long string name
# - RUDDER_NODE_IPS: space separated list of IPs of that node
# - RUDDER_AGENT_TYPE: agent type ("cfengine-community" or "dsc")

# Errors code on hooks are interpreted as follow:
# - 0     : success, no log (appart if debug one)          , continue to next hook
# - 1-31  : error  , error   log in /var/log/rudder/webapp/, stop processing
# - 32-63 : warning, warning log in /var/log/rudder/webapp/, continue to next hook
# - 64-255: reserved for futur use case. Behavior may change without notice.

exit 0
