= Rust dev environment

== General information

The compiler version used to build the projects are
set in a `rust-toolchain` file in each project root, but
we strive to keep compiler versions in sync between projects.
We can rely on recent Rust compilers as we control the version
installed on our package builders.

We use dependencies from `crates.io` directly. Be careful to include `Cargo.lock` in repositories,
and to use `--locked` for build and test commands.

The Rust projects share a common base Makefile (`rust.makefile` at the repository root).

== Development environment

=== Rust toolchain

The easiest way to install and manage
Rust toolchains locally is to use https://rustup.rs[rustup].
It will install the latest stable toolchain by default, and download
additional toolchains when needed (based on the `rust-toolchain` file).

=== IDE/Editor

https://areweideyet.com/[Good IDEs for Rust development] include IntelliJ IdeaC, Visual Studio Code or
any editor supporting LSP.

When using VS Code or another LSP-based editor integration, https://github.com/rust-analyzer/rust-analyzer#language-server-quick-start[rust-analyzer]
should be used.

=== Tools

Other useful tools:

```bash
rustup component add rustfmt # to format code, use with "cargo fmt"
rustup component add clippy  # various linters, use with "cargo clippy"
cargo install cargo-deny     # to list known vulnerabilities and check licenses in dependencies
cargo install cargo-outdated # to list outdated dependencies
cargo install cargo-update   # to update cargo-installed tools
cargo install cargo-tree     # to see the tree of dependencies
cargo install cargo-benchcmp # to compare benchmarks results
cargo install sccache        # to share compilation cache locally between projects
cargo install cargo-nextest  # to run tests in parallel (when possible)
```
