//! Rudder API `GET` endpoints from the OpenAPI source, indexed by `build.rs`, for the generic
//! `api_search` and `api_get` tools (the escape hatch for what no dedicated tool covers).

use serde::Deserialize;

/// Upper bound on search results
const MAX_RESULTS: usize = 15;
/// Upper bound on an `api_get` answer: raw endpoints can return megabytes
const MAX_RESPONSE: usize = 20_000;

#[derive(Debug, Deserialize)]
pub struct Endpoint {
    /// Template, e.g. `/nodes/{nodeId}`
    pub path: String,
    summary: String,
    description: String,
    operation_id: String,
    tags: Vec<String>,
    parameters: Vec<Parameter>,
}

#[derive(Debug, Deserialize)]
struct Parameter {
    name: String,
    /// `path` or `query`
    location: String,
    required: bool,
    description: String,
    kind: String,
    values: Vec<String>,
}

impl Endpoint {
    /// Names of the query parameters this endpoint documents
    pub fn query_parameters(&self) -> impl Iterator<Item = &str> {
        self.parameters
            .iter()
            .filter(|p| p.location == "query")
            .map(|p| p.name.as_str())
    }

    fn describe(&self) -> String {
        let mut lines = vec![format!(
            "GET {} ({}): {}",
            self.path, self.operation_id, self.summary
        )];
        if !self.description.is_empty() && self.description != self.summary {
            lines.push(format!("  {}", self.description));
        }
        for p in &self.parameters {
            let required = if p.required { ", required" } else { "" };
            let values = if p.values.is_empty() {
                String::new()
            } else {
                format!(", one of: {}", p.values.join(", "))
            };
            lines.push(format!(
                "  - {} ({} {}{required}{values}): {}",
                p.name, p.location, p.kind, p.description
            ));
        }
        lines.join("\n")
    }
}

#[derive(Debug)]
pub struct ApiIndex(Vec<Endpoint>);

impl ApiIndex {
    pub fn embedded() -> Self {
        Self(
            serde_json::from_str(include_str!(concat!(env!("OUT_DIR"), "/api_index.json")))
                .expect("index generated by build.rs is valid"),
        )
    }

    /// Endpoints matching every word of `query` (in path, summary, description, operation id or
    /// tags), with their parameters
    pub fn search(&self, query: &str) -> String {
        let words: Vec<String> = query.split_whitespace().map(str::to_lowercase).collect();
        let found: Vec<&Endpoint> = self
            .0
            .iter()
            .filter(|e| {
                let haystack = format!(
                    "{} {} {} {} {}",
                    e.path,
                    e.summary,
                    e.description,
                    e.operation_id,
                    e.tags.join(" ")
                )
                .to_lowercase();
                words.iter().all(|w| haystack.contains(w.as_str()))
            })
            .collect();
        if found.is_empty() {
            return format!(
                "no GET endpoint matches '{query}'. Try fewer or other words (e.g. a resource: nodes, rules, directives, groups, techniques, parameters, compliance)"
            );
        }
        let mut result: Vec<String> = found
            .iter()
            .take(MAX_RESULTS)
            .map(|e| e.describe())
            .collect();
        if found.len() > MAX_RESULTS {
            result.push(format!(
                "... {} more endpoints: add words to narrow the search",
                found.len() - MAX_RESULTS
            ));
        }
        result.join("\n")
    }

    /// The documented endpoint `path` (e.g. `nodes/root`) is an instance of, and the path to call.
    /// Literal segments must match exactly, and template segments only take one plain segment, so
    /// only documented `GET` endpoints can be reached. The most specific template wins
    /// (`/nodes/pending` over `/nodes/{nodeId}`).
    pub fn resolve(&self, path: &str) -> Result<(&Endpoint, String), String> {
        let path = path
            .trim_start_matches('/')
            .trim_start_matches("rudder/api/latest/");
        if path.contains(['?', '#', '%', '\\']) {
            return Err("give the path alone, without query or encoded characters: query parameters go in `query`".to_owned());
        }
        let segments: Vec<&str> = path.trim_end_matches('/').split('/').collect();
        if segments.iter().any(|s| !is_segment(s)) {
            return Err(format!("'{path}' is not a valid API path"));
        }
        self.0
            .iter()
            .filter_map(|endpoint| {
                let template: Vec<&str> =
                    endpoint.path.trim_start_matches('/').split('/').collect();
                if template.len() != segments.len() {
                    return None;
                }
                let mut literals = 0;
                for (t, s) in template.iter().zip(&segments) {
                    if t.starts_with('{') && t.ends_with('}') {
                        continue;
                    }
                    if t != s {
                        return None;
                    }
                    literals += 1;
                }
                Some((literals, endpoint))
            })
            .max_by_key(|(literals, _)| *literals)
            .map(|(_, endpoint)| (endpoint, segments.join("/")))
            .ok_or_else(|| {
                format!("'{path}' is not a documented GET endpoint: find it with `api_search`")
            })
    }
}

/// The response `data` (without the `action` / `result` envelope), pretty-printed and cut to
/// `MAX_RESPONSE` characters
pub fn trim_response(body: &str) -> String {
    let text = match serde_json::from_str::<serde_json::Value>(body) {
        Ok(mut response) if !response["data"].is_null() => {
            serde_json::to_string_pretty(&response["data"].take()).unwrap_or_default()
        }
        _ => body.to_owned(),
    };
    let length = text.chars().count();
    if length <= MAX_RESPONSE {
        return text;
    }
    let cut: String = text.chars().take(MAX_RESPONSE).collect();
    format!(
        "{cut}\n... cut, {} more characters: narrow the request with the endpoint's parameters (e.g. `include`, `level`, `where`)",
        length - MAX_RESPONSE
    )
}

/// One path segment: ids, hostnames, versions (`1.0`), no traversal
fn is_segment(segment: &str) -> bool {
    !segment.is_empty()
        && segment != "."
        && segment != ".."
        && segment
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || "-_.:@~".contains(c))
}

#[cfg(test)]
mod tests {
    use pretty_assertions::assert_eq;

    use super::*;

    #[test]
    fn index_is_built_from_the_spec() {
        let index = ApiIndex::embedded();
        assert!(index.0.len() > 50, "{} endpoints", index.0.len());
        let node = index
            .0
            .iter()
            .find(|e| e.path == "/nodes/{nodeId}")
            .unwrap();
        assert_eq!(node.operation_id, "nodeDetails");
        assert_eq!(node.query_parameters().collect::<Vec<_>>(), ["include"]);
    }

    #[test]
    fn search_matches_all_words() {
        let index = ApiIndex::embedded();
        let result = index.search("node details");
        assert!(
            result.contains("GET /nodes/{nodeId} (nodeDetails)"),
            "{result}"
        );
        assert!(result.contains("- include (query string)"), "{result}");
        assert!(index.search("zzz nothing").starts_with("no GET endpoint"));
    }

    #[test]
    fn responses_are_unwrapped_and_cut() {
        assert_eq!(
            trim_response(r#"{"action":"x","result":"success","data":{"a":1}}"#),
            "{\n  \"a\": 1\n}"
        );
        let long = format!(r#"{{"data":"{}"}}"#, "x".repeat(MAX_RESPONSE * 2));
        let trimmed = trim_response(&long);
        assert!(
            trimmed.contains("... cut, "),
            "{}",
            &trimmed[trimmed.len() - 200..]
        );
        assert!(trimmed.chars().count() < MAX_RESPONSE + 200);
    }

    #[test]
    fn resolve_documented_paths_only() {
        let index = ApiIndex::embedded();
        let (endpoint, path) = index.resolve("/nodes/root").unwrap();
        assert_eq!(
            (endpoint.path.as_str(), path.as_str()),
            ("/nodes/{nodeId}", "nodes/root")
        );
        // Literal segments win over templates
        let (endpoint, _) = index.resolve("nodes/pending").unwrap();
        assert_eq!(endpoint.path, "/nodes/pending");
        // Full paths are accepted
        assert!(index.resolve("/rudder/api/latest/rules").is_ok());

        for bad in [
            "nodes/../system/info",
            "nodes/root?include=full",
            "nodes/%2e%2e",
            "nodes/root/../../x",
            "system/doesnotexist",
            "",
        ] {
            assert!(index.resolve(bad).is_err(), "{bad} was accepted");
        }
    }
}
