# generated by rudderc
# @name Simple block
# @version 1.0

function Simple-Block {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"d58aec44-675b-48fd-985e-499ec4c5e525"
  $common_params = @{
    ClassPrefix = "tmp"
    ComponentKey = "tmp"
    ComponentName = "File absent"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  if ($localContext.evaluate("debian")) {
    $call_params = @{
      Path = "tmp"
      PolicyMode = $PolicyMode
    }
    $call = File-Absent @call_params
    $compute_params = $common_params + @{
      MethodCall = $call
    }
    $context = Compute-Method-Call @compute_params
    $localContext.merge($context)
  }
  else {
    Rudder-Report-NA @common_params
  }
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"7ba6a2ec-ebb5-4445-b7d4-9cec5a2e52a9"
  $common_params = @{
    ClassPrefix = "tmp"
    ComponentKey = "tmp"
    ComponentName = "File absent"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  if ($localContext.evaluate("debian")) {
    $call_params = @{
      Path = "tmp"
      PolicyMode = $PolicyMode
    }
    $call = File-Present @call_params
    $compute_params = $common_params + @{
      MethodCall = $call
    }
    $context = Compute-Method-Call @compute_params
    $localContext.merge($context)
  }
  else {
    Rudder-Report-NA @common_params
  }
}
