# generated by rudderc
# @name deprecated
# @version 1.0

function Deprecated {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"3a5c97e5-0b4d-4341-b880-262ccd51f453"
  $common_params = @{
    ClassPrefix = "tmp"
    ComponentKey = "tmp"
    ComponentName = "Directory create"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  $call_params = @{
    Path = "tmp"
    PolicyMode = $PolicyMode
  }
  $call = Directory-Create @call_params
  $compute_params = $common_params + @{
    MethodCall = $call
  }
  $context = Compute-Method-Call @compute_params
  $localContext.merge($context)
}
