# generated by rudderc
# @name deprecated
# @version 1.0

function Deprecated {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Switch]$AuditOnly
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $LocalClasses = New-ClassContext
  $ResourcesDir = $PSScriptRoot + "\resources"
  $ReportId = $ReportIdBase+"3a5c97e5-0b4d-4341-b880-262ccd51f453"
  $LocalClasses = Merge-ClassContext $LocalClasses $(Directory-Create -Path "tmp" -ComponentName "Directory create" -ReportId $ReportId -TechniqueName $TechniqueName -Report:$true -AuditOnly:$AuditOnly).get_item("classes")
}
