# generated by rudderc
# @name Inner block
# @version 1.0

function Inner-Block {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"cb2881a0-11c8-4040-8ac0-3751d10146b7"
  $common_params = @{
    ClassPrefix = "tmp"
    ComponentKey = "tmp"
    ComponentName = "File absent"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  if ($localContext.evaluate("(debian).(centos)")) {
    $call_params = @{
      Path = "tmp"
      PolicyMode = $PolicyMode
    }
    $call = File-Absent @call_params
    $compute_params = $common_params + @{
      MethodCall = $call
    }
    $context = Compute-Method-Call @compute_params
    $localContext.merge($context)
  }
  else {
    Rudder-Report-NA @common_params
  }
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"df319f6f-3573-4b7e-95e5-f10dcd3f7a3f"
  $common_params = @{
    ClassPrefix = "tmp"
    ComponentKey = "tmp"
    ComponentName = "File absent"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  if ($localContext.evaluate("(debian).(centos)")) {
    $call_params = @{
      Path = "tmp"
      PolicyMode = $PolicyMode
    }
    $call = File-Present @call_params
    $compute_params = $common_params + @{
      MethodCall = $call
    }
    $context = Compute-Method-Call @compute_params
    $localContext.merge($context)
  }
  else {
    Rudder-Report-NA @common_params
  }
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"e6ccdd10-642b-494a-9b06-27ce509f579f"
  $common_params = @{
    ClassPrefix = "tmp2"
    ComponentKey = "tmp2"
    ComponentName = "File absent"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  if ($localContext.evaluate("((debian).(debian_10)).(linux)")) {
    $call_params = @{
      Path = "tmp2"
      PolicyMode = $PolicyMode
    }
    $call = File-Absent @call_params
    $compute_params = $common_params + @{
      MethodCall = $call
    }
    $context = Compute-Method-Call @compute_params
    $localContext.merge($context)
  }
  else {
    Rudder-Report-NA @common_params
  }
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"7ba6a2ec-ebb5-4445-b7d4-9cec5a2e52a9"
  $common_params = @{
    ClassPrefix = "tmp2"
    ComponentKey = "tmp2"
    ComponentName = "File absent"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  if ($localContext.evaluate("(debian).(debian_10)")) {
    $call_params = @{
      Path = "tmp2"
      PolicyMode = $PolicyMode
    }
    $call = File-Present @call_params
    $compute_params = $common_params + @{
      MethodCall = $call
    }
    $context = Compute-Method-Call @compute_params
    $localContext.merge($context)
  }
  else {
    Rudder-Report-NA @common_params
  }
}
