# generated by rudderc
# @name condition useless brackets
# @version 1.0

function Condition-Useless-Brackets {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Rudder.PolicyMode]$PolicyMode
  )

  $ReportIdBase = $reportId.Substring(0,$reportId.Length-1)
  $localContext = [Rudder.Context]::new()
  $resourcesDir = $PSScriptRoot + "\resources"
  # --------------Method Call--------------- #
  $ReportId = $ReportIdBase+"b75bd5d3-8304-4cd6-8689-2ba650c7c42a"
  $common_params = @{
    ClassPrefix = "tagname"
    ComponentKey = "tagname"
    ComponentName = "DSC built-in resource"
    PolicyMode = $PolicyMode
    ReportId = $ReportId
    TechniqueName = $TechniqueName
  }
  if ($localContext.evaluate("!debian|linux|ubuntu.windows|linux|ubuntu")) {
    $call_params = @{
      PolicyMode = $PolicyMode
      ResourceName = "file"
      ScriptBlock = @'
exists
'@
      Tag = "tagname"
    }
    $call = Dsc-Built-In-Resource @call_params
    $compute_params = $common_params + @{
      MethodCall = $call
    }
    $context = Compute-Method-Call @compute_params
    $localContext.merge($context)
  }
  else {
    Rudder-Report-NA @common_params
  }
}
