# generated by rudderc
# @name condition useless brackets
# @version 1.0

function Condition-Useless-Brackets-Technique {
  [CmdletBinding()]
  param (
    [Parameter(Mandatory=$True)]
    [String]$ReportId,
    [Parameter(Mandatory=$True)]
    [String]$TechniqueName,
    [Switch]$AuditOnly
  )

  $LocalClasses = New-ClassContext
  $ResourcesDir = $PSScriptRoot + "\resources"
  $Class = "!debian|linux|ubuntu.windows|linux|ubuntu"
  if (Evaluate-Class $Class $LocalClasses $SystemClasses) {
    $LocalClasses = Merge-ClassContext $LocalClasses $(Dsc-Built-In-Resource -Tag "tagname" -ResourceName "file" -ScriptBlock @'
exists
'@ -ComponentName "DSC built-in resource" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly).get_item("classes")
  }
  else {
    _rudder_common_report_na -ComponentName "DSC built-in resource" -ComponentKey "tagname" -Message "Not applicable" -ReportId $ReportId -TechniqueName $TechniqueName -AuditOnly:$AuditOnly
  }
}
